- README.md
- elliott
Now that elliott is a standalone project, this notation makes less
sense. So let's all save the keystrokes and use the shorter notation.
> Update command names to remove 'advisory:' notation

- elliott
- elliottlib/bugzilla.py
- elliottlib/constants.py
Adds a --status parameter for the find-bugs command. This also sets
the default for bug sweeps to include both MODIFIED and VERIFIED bugs
> Search for arbitrary status

- elliott
- elliottlib/bugzilla.py
- elliottlib/constants.py
This removes bugzilla values from the source code and into an
ocp-build-data like datastore. In addition to moving everything to
a single source of truth, this will enable non-OpenShift teams to
use the bugzilla functions of elliott in the future.
> Remove all hardcoded bugzilla values

- elliott
- elliottlib/constants.py
- elliottlib/errata.py
This removes errata tool values from the source code and into an
ocp-build-data like datastore. In addition to moving everything to
a single source of truth, this will enable non-OpenShift teams to
use the errata tool functions of elliott in the future.
> Move errata tool template information out of code

- README.md
- elliott
- elliottlib/bzutil.py
- elliottlib/bzutil_test.py
- elliottlib/constants.py
- requirements.txt
Move away from using shell callouts to the python-bugzilla cli and use the actual library. Also remove the deprecated bug transition searches now that we can add VERIFIED bugs regardless of the path they took to get there.
> Transition to using python-bugzilla library

- elliott
- elliottlib/errata.py
Now that we are using the errata-tool library instead of calling
the API directly, we get different exceptions when the user
does not have a kerb ticket.
> Correct exception handling for kerb

- elliott
- elliottlib/schema_group.yml
To make bug sweeping happen more frequently and automatically we are
adding this little bit of functionality. If a value is defined in
ocp-build-data for .advisories.<TYPE> (type=rpm, image, security) then
you can have elliott attach bugs to that advisory by selecting it on
the command line.
We have played around with implementing logic to automatically
determine the right advisory for this but it hasn't come to fruition
yet. Instead we're going to try this little workaround instead.
----
Also adds some color to `find-bugs` and corrects a busted example.
> Elliott can use a default advisory if defined in ocp-build-data

- .gitignore
- elliott
- elliottlib/cli_opts.py
- elliottlib/cli_opts_test.py
fixes https://github.com/openshift/elliott/issues/34#issuecomment-484076209
now it supports multiple ways
```
➜  elliott git:(master) ./elliott --group openshift-4.0 find-bugs --id 123,345 --id 1234 --id 123 --id 3,43,3,2,4,6
```
> add --id parse support comma

- elliott
Repair bugs has been updated to now include:
* Support for the `--use-default-advisory` option
* Clearer help text
* A `--noop` (`--dry-run`) mode
* Looking up bugs in parallel
> Repair-bugs: New options, doc refresh, and speed improvements.

- elliottlib/brew.py
- elliottlib/brew_test.py
- elliottlib/container_test.py
- elliottlib/errata.py
- elliottlib/errata_test.py
- elliottlib/exectools_test.py
- elliottlib/image_test.py
- elliottlib/metadata_test.py
- elliottlib/rpmcfg_test.py
- elliottlib/runtime.py
I'm not _fixing_ broken tests on this PR, simply skipping the ones currently failing.
Just as it was with `flake8`, this is also a preparatory step to accomplish [ART-547](https://jira.coreos.com/browse/ART-547) (Run tox on Travis)
The only thing I actually needed to fix were some import errors:
elliottlib's `exceptions` module was probably conflicting with Python's builtin one.
> [ART-544] (part 3 of 4) Make current tests pass

- .ci/Dockerfile
- .travis.yml
On this PR I'm making Travis run `tox` inside a container, but during development
we have a choice of running either inside the container or directly on the host.
$ podman build -f .ci/Dockerfile -t elliott-ci-env .
$ podman run -it --rm -v $(pwd):/code -w /code elliott-ci-env
or simply:
$ tox
Related ticket:
https://jira.coreos.com/browse/ART-547
> [ART-544] (part 4 of 4) Run `tox` on Travis

- README.md
I attempted to install elliott (via `pip install rh-elliott`) in a fresh Fedora 29, and it didn't succeed until I had installed all the packages listed on this PR.
Just thought it might be useful to have such dependencies list on the README for future reference.
Worth to mention that those are only the dependencies I didn't have installed on my machine, but I noticed that the installation also relies on `gcc` (and probably relies on even more packages that were already present).
> List installation dependencies on README

- elliott
- elliottlib/errata.py
- elliottlib/util.py
I might actually rather go in the direction of using the YYYY-MM-DD
format for the date, and simply reformat it when handing off to
errata-tool. But I could also see an argument that it's good for elliott
to use a consistent format as errata does.
Either way the help and errors should not give users the wrong format.
> correct misleading date format info

- elliott
Make behavior consistent with `find-builds --kind rpm`.
Related ticket: https://jira.coreos.com/browse/ART-1091
> [ART-1091] Filter already attached image builds

- Jenkinsfile
Jenkins changed this behavior, just pulling the latest image if explicitly specified: https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/199
> Always pull latest CI image

- elliott
- elliottlib/cli/list_cli.py
Move elliott 'list' commands into cli folder
```
[dev@492a2d100413 elliott]$ ./elliott -g openshift-4.2 list
2019-Oct-29 QE              OpenShift Container Platform 4.2.1 OLM Operators metadata update                 https://errata.devel.redhat.com/advisory/47337
2019-Oct-29 QE              OpenShift Container Platform 4.2.1 extras update                                 https://errata.devel.redhat.com/advisory/47336
2019-Oct-29 QE              OpenShift Container Platform 4.2.1 images update                                 https://errata.devel.redhat.com/advisory/47335
2019-Oct-29 QE              OpenShift Container Platform 4.2.1 bug fix update                                https://errata.devel.redhat.com/advisory/47334
2019-Oct-16 NEW_FILES       OpenShift Container Platform 4.2.z OLM …
```
> Move elliott 'list' commands into cli 

- elliottlib/bzutil.py
- elliottlib/cli/create_cli.py
- elliottlib/constants.py
- elliottlib/errata.py
- tests/test_bzutil.py
According to ART-1192, if a tracking bug has `unspecified` severity,
we need to check the severity of the flaw bugs. If all flaw bugs have `unspecified` severity, we will default the impact to `Low` (ProdSec can correct it later).
Also makes the errata_tool lib honor the Errata Tool URL constant `elliottlib.constants.errata_url`.
You can test this PR by creating an RHSA using a tracking bug with `unspecified` severity. For example, bug 1757044:
- Without this PR:
``` bash
$ elliott -g openshift-4.2 create -k image --impetus cve -t RHSA --date 2019-Nov-05 --assigned-to openshift-qe-errata@redhat.com --manager vlaad@redhat.com --package-owner lmeyer@redhat.com --bugs 1757044
$ elliott -g openshift-4.2 create -k image --impetus cve -t RHSA --date 2019-Nov-05 --assigned-to …
```
> ART-1192: Fix RHSA creation when no severity set on the tracking bug

- elliottlib/cli/tarball_sources_cli.py
Per https://projects.engineering.redhat.com/browse/RCM-68294,
it would be more convenient for RCM if the file permissions
of tarball sources include read for other (o+r).
This PR uses `shutils.copyfile` rather than `shutils.copy2` to honor the umask for creating local tarballs,
and changes the instructions of sending to rcm-guest to explicitly set `r` for files and `rx` for directories.
> Set correct permissions on rcm-guest for tarball sources

- README.md
- tox.ini
This branch is used for Python 3 migration. Python 3 test is enabled on this branch.
We periodically synchronize the master with this branch until we get everything working on Python 3.
> Python 3: Create python-3 branch for migration

- .devcontainer/settings.yaml
- elliottlib/bzutil.py
- elliottlib/cli/create_cli.py
- elliottlib/constants.py
- elliottlib/errata.py
- tests/test_bzutil.py
- tests/test_errata.py
- Provide more correct boilerplate text for different kinds of advisories.
See https://github.com/openshift/ocp-build-data/pull/183 for example.
- Raise an error if any bug is not viable:
- For RHBA, assert bugs are in one of `MODIFIED`, `ON_QA`, or `VERIFIED` state and not attached to any other advisories.
- For RHSA, perform the same checks as RHBA then validate they are tracker bugs.
- When running without `--yes` (preview mode), also print the full list of bugs that would be attached.
- CLI: Add help text and alias `--bug` for option `--bugs`
1. This PR doesn't prevent users from attaching a security bug to an RHBA/RHEA. Not sure if we should do that.
2. Boilerplate text updates:
- 4.2 https://github.com/openshift/ocp-build-data/pull/183
- 4.1 …
> ART-1011 improve rhsa creation

- elliott
- elliottlib/bzutil.py
**Note:** This PR is just rebased https://github.com/openshift/elliott/pull/33
find-bugs has value as it lets us define exactly which bugs will be
attached to an advisory based on declaritive filters. This update will
allow users to see more useful information about those bugs other than
just the IDs.
```
$ elliott --group=openshift-4.1 find-bugs --id 1755350
2019-10-14 15:41:32,183 INFO Data clone directory already exists, checking commit sha
2019-10-14 15:41:36,647 INFO git@gitlab.cee.redhat.com:openshift-art/ocp-build-data.git is already cloned and latest
2019-10-14 15:41:36,747 INFO Using branch from group.yml: rhaos-4.1-rhel-7
Found 1 bugs: 1755350
```
```
$ elliott --group=openshift-4.1 find-bugs --id 1755350 --report
2019-10-14 15:41:20,802 INFO Data clone directory already exists, …
```
> Update find-bugs to generate a report

- tests/test_assertion.py
- tests/test_brew.py
- tests/test_cli.py
- tests/test_errata.py
- tests/test_exectools.py
- tests/test_imagecfg.py
- tests/test_pushd.py
- tests/test_runtime.py
1. Use absolute imports.
2. Removes logging hacks from `tests/test_brew.py` (Not sure what is does and it causes troubles with `pytest`).
3. Rename `test_image.py` to `test_imagecfg.py` to be consistent with #69.
> Refactor unit test imports for Python 3 migration

- elliottlib/cli/__main__.py
- elliottlib/cli/advisory_images_cli.py
- elliottlib/constants.py
- elliottlib/errata.py
- tests/test_errata.py
[ART-670](https://jira.coreos.com/browse/ART-670): Generate Image List for CCS (docs team)
```
$ elliott -g openshift-4.2 generate-ccs-image-list
2019-11-21 14:57:08,922 INFO Data clone directory already exists, checking commit sha
2019-11-21 14:57:09,496 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
2019-11-21 14:57:09,598 INFO Using branch from group.yml: rhaos-4.2-rhel-7
Default advisory detected: 48465                                                               
#########                                                                                      
openshift4/ose-cluster-autoscaler:v4.2.8-201911190952       
openshift4/ose-baremetal-machine-controllers:v4.2.8-201911190952
openshift4/ose-cluster-monitoring-operator:v4.2.8-201911190952 …
```
> [ART-670] Generate Image List for CCS (docs team)

- elliottlib/cli/rpmdiff_cli.py
- elliottlib/rpmdiff.py
- tests/test_rpmdiff.py
I mistakenly used incorrect parameter names and forgot to honor the `limit` parameter.
Also change the function name to `list_waivers`.
> Fix rpmdiff list waivers API call

- .devcontainer/dev.Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/krb5-redhat.conf
- requirements-dev.txt
1. Bump `oc` version to 4.2.8.
2. Remove most RPM based Python packages and use `pip` versions instead (to be consistent with How OpenShift ART team actually installs dependencies).
3. Move Kerberos ccache configuration from environment variable to configuration file, so that the configuration will not lost after switching user with `sudo`.
4. Install GitLens plugin for VSCode on dev container start.
> Update dev container configuration

- requirements.txt
So currenlty since pygit (https://pypi.org/project/pygit2/0.28.2/\#history) update on Dec 6,2019 with version 1.0.0 our pip install command will be failed see issue https://github.com/openshift/elliott/issues/100 for details error logs, tempeoray make pygit2 version sticked to older version
Fix https://github.com/openshift/elliott/issues/100
> temp fix for pygit2

- elliottlib/cli/__main__.py
- elliottlib/cli_opts.py
- elliottlib/config.py
- elliottlib/dotconfig.py
- elliottlib/errata.py
- elliottlib/gitdata.py
- elliottlib/model.py
- elliottlib/openshiftclient.py
- elliottlib/runtime.py
- tests/test_assertion.py
- tests/test_brew.py
- tests/test_errata.py
- tests/test_tarball_sources.py
split out a couple of other patches and have a long patch set of different python 2 vs 3 fixes/changes
tox -e py3 now works and passes locally
Most of these should be py2 backward compatible but some changes may impact runtime usage of the tool, more testing is required before anything can be said about whether it works or not.
Related: issue #84
> python 3 - compatiblity fixes

- elliottlib/cli/rpmdiff_cli.py
- functional_tests/README.md
- functional_tests/constants.py
- functional_tests/test_advisory_images.py
- functional_tests/test_change_state.py
- functional_tests/test_create.py
- functional_tests/test_find_bugs.py
- functional_tests/test_find_builds.py
- functional_tests/test_find_cve_trackers.py
- functional_tests/test_get.py
- functional_tests/test_list.py
- functional_tests/test_poll_signed.py
- functional_tests/test_rpmdiff.py
- functional_tests/test_tarball_sources.py
- functional_tests/test_verify_payload.py
- setup.py
- tox.ini
Add functional test suite for Elliott. The test suite works by invoking `elliott` as a subprocess then checking for the exit code and output.
Currently the test suite doesn't mock any services, such as Errata Tool, Bugzilla, Brew, etc, but interacts with real production services. This is not perfect but can significantly help our Python 3 migration as a fuse.
See `functional_tests/README.md` for more information and known issues.
> Add functional tests

- elliottlib/cli/__main__.py
- elliottlib/cli/advisory_impetus_cli.py
Part of the logic required by [ART-818](https://issues.redhat.com/browse/ART-818) depends on knowing an advisory's *impetus*.
This PR introduces a new CLI option to easily fetch the impetus of a given advisory.
```
$ ./elliott advisory-impetus -a 48465
standard
```
```
$ ./elliott -g openshift-4.4 advisory-impetus --use-default-advisory image
2020-01-03 14:31:50,285 INFO Data clone directory already exists, checking commit sha
2020-01-03 14:31:50,303 INFO Cloning config data from https://github.com/openshift/ocp-build-data.git
2020-01-03 14:31:51,709 INFO Using branch from group.yml: rhaos-4.4-rhel-7
Default advisory detected: 47983
ga
```
> [ART-818] New "get advisory impetus" CLI command

- elliottlib/brew.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/imagecfg.py
previously we list all the images using brew latest-build one by one, that’s about 130-150 command call which is not very efficient.
in this PR, we change brew latest-build tag componet_name into directly API call and avoid list every componet indivitually instead
we compare the list returned from API with image_meta
> [ART-1342] speed up get_latest_build_info and solve the multi branch/tag mapping issue

- elliottlib/brew.py
- elliottlib/bzutil.py
- elliottlib/cli/__main__.py
- elliottlib/cli/create_cli.py
- elliottlib/cli/puddle_advisories_cli.py
- elliottlib/cli/rpmdiff_cli.py
- elliottlib/dotconfig.py
- elliottlib/errata.py
- elliottlib/exectools.py
- elliottlib/gitdata.py
- elliottlib/model.py
- elliottlib/runtime.py
- elliottlib/tarball_sources.py
- functional_tests/test_find_bugs.py
- functional_tests/test_find_cve_trackers.py
- functional_tests/test_poll_signed.py
- functional_tests/test_rpmdiff.py
- requirements.txt
1. Don't override builtin `str` for Python 2 with `builtins.str` because the later type is a wrapper class which could break yaml deserialization.
2. Always return `str` for `__str__` and `__repr__` methods rather than unicode for Python 2.
3. Fix non-textmode error message formatting for `exectools.cmd_gather`.
4. Use fine-grained `pygit2` version locking.
5. Eliminate `assertRegexpMatches` deprecation warnings on Python 3 by using the `six` wrapper.
> Additional fixes for better Python 2/3 compatibility

- .devcontainer/dev.Dockerfile
1. Bump base image to Fedora 31 (RCM has upgraded their tools with Fedora 31 support).
2. Bump oc version to 4.2.16.
> Update Dev Container

- elliottlib/errata.py
Just a quick patch to get 4.5 GA advisories done through buildvm.
> [ART-1361] boilerplates key will always exist on file, regardless of GA impetus

- elliottlib/cli/__main__.py
Looks like cf_pm_score is not always present and encoding string as bytes breaks output (Besides that we shouldn't assume bug summary always contains ascii text, which can cause `UnicodeEncodeError: 'ascii' codec can't encode...`)
> ART-1662: Fix find-bugs --mode sweep --report

- elliottlib/brew.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/errata.py
- tests/test_brew.py
- Continuously fetches advisory comments until empty so the metadata
comment will not be missed.
- Always attaches builds given by `--build`.
- Adds `--allow-attached` option to bypass the check for attached
builds.
- Adds additional option checks
- Combines multithreaded Brew API calls to one multicall.
- Other minor fixes.
Tested with attaching extra images to
https://errata.devel.redhat.com/advisory/47985.
> ART-1776: Fix build sweep issue where advisory comments are paginated

- elliottlib/cli/advisory_images_cli.py
- elliottlib/errata.py
- tests/test_errata.py
Add `--raw` to elliott advisory-images. This outputs the list of nvrs as attached to the advisory. This can be used in e.g. pipes.
> Add raw advisory-images output

- elliottlib/cli/tarball_sources_cli.py
Original command:
```
$ rsync -avz --chmod=go+rX /mnt/nfs/home/jenkins/container-sources/ ocp-build@rcm-guest.app.eng.bos.redhat.com:/mnt/rcm-guest/ocp-client-handoff/
sending incremental file list
./
rsync: failed to set permissions on "/mnt/rcm-guest/ocp-client-handoff/.": Operation not permitted (1)
sent 7639 bytes  received 154 bytes  5195.33 bytes/sec
total size is 155281575  speedup is 19925.78
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]
$ echo $?
23
```
Only removing `--chmod` flag:
```
$ rsync -avz /mnt/nfs/home/jenkins/container-sources/ ocp-build@rcm-guest.app.eng.bos.redhat.com:/mnt/rcm-guest/ocp-client-handoff/
sending incremental file list
./
rsync: failed to set permissions on …
```
> Don't try to set permissions on tarball rsync

- elliottlib/cli/find_builds_cli.py
This PR introduced an option for find-builds just to remove those unsinged builds since new workflow change in z-stream release.
cc @sosiouxme @thiagoalessio @vfreex 
```
[dev@8850aaf9493f elliott]$ elliott --group openshift-4.3 find-builds -k image -b oauth-server-container-v4.3.22-202005212137 -a 55017 --remove
2020-05-22 11:17:09,669 INFO Data clone directory already exists, checking commit sha
2020-05-22 11:17:12,355 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
2020-05-22 11:17:12,490 INFO Using branch from group.yml: rhaos-4.3-rhel-7
Fetching tags for builds...Fetching builds from Errata: Hold on a moment, fetching buildinfos from Errata Tool...
[*]
[*]
Remvoing from advisory 55017...
Removed build(s) successfully: …
```
> make find-buidls has option `--remove` to remove builds from advisory

- elliottlib/cli/__main__.py
- elliottlib/cli/change_state_cli.py
```
[dev@1f06086f7f33 elliott]$ elliott change-state  --state QE --advisory 53516 
ElliottFatalError("Error: Could not change 'SHIPPED_LIVE' advisory 53516, group.yml is probably pointing at old one")
```
wrap up https://issues.redhat.com/browse/ART-1066
> make some change to change_state to reflect more accurate error messages

- elliottlib/brew.py
- elliottlib/cli/__main__.py
- elliottlib/cli/change_state_cli.py
- elliottlib/cli/tag_builds_cli.py
- elliottlib/errata.py
This PR reimplements [ocp-tag-signed-errata-builds.py](https://github.com/openshift/aos-cd-jobs/blob/6b4877d519f20cadad0f65b2f185cb7cf2b4edde/jobs/build/signed-compose/ocp-tag-signed-errata-builds.py),
which tags builds on advisories into a Brew tag for creating signed
compose.
Comparing with the original implementation, this PR has the following
advantages:
- Only tag RPMs that are on specified advisories rather than all open advisories. Advisory IDs can be given with `--advisory` or ocp-build-data. This is to avoid tagging unwanted builds like https://issues.redhat.com/browse/ART-1306.
- Don't tag images. It is not necessary.
- Leverage the Brew multicall API to improve the tagging performance.
- When waiting for the tagging tasks to finish, mimic the behavior of `brew tagBuild` …
> Add `tag-builds` command to replace ocp-tag-signed-errata-builds.py

- .devcontainer/dev.Dockerfile
- .devcontainer/devcontainer.json
For VSCode users, this will dramatically improve the autocompete experience comparing with the default jedi language server.
> Dev container: Use Microsoft Python Language Server for autocomplete

- .gitignore
- elliottlib/cli/find_builds_cli.py
- elliottlib/imagecfg.py
https://issues.redhat.com/browse/ART-745
1. extend property of ImageMetadata to support parse for_payload field in ocp-buil-data (currently only 4.5 merged)
2. add two flags (`--payload` `--non-payload`) to support attach only payload images or only non-payload images, if not specify attach all (backward compatibility)
3. test result file: https://gist.githubusercontent.com/shiywang/82af57eda3a6b7700df2a96f645e82f3/raw/27de59cbb514060521c356d56e516a9c000f5823/gistfile1.txt
```
[dev@33036d511566 elliott]$  elliott -g openshift-4.5 find-builds -k image --allow-attached --payload 
2020-07-27 10:54:44,615 INFO Data clone directory already exists, checking commit sha
2020-07-27 10:54:47,380 INFO https://github.com/openshift/ocp-build-data.git is already cloned and latest
2020-07-27 …
```
> [ART-745] Payload nonpayload

- elliottlib/bzutil.py
- elliottlib/cli/__main__.py
- elliottlib/runtime.py
- elliottlib/util.py
3.y: Sweep all bugs into the rpm advisory.
4.y: Sweep optional operator bugs into extras advisory and other bugs into main image advisory.
@sosiouxme JIRA ART-997 doesn't describe which components/github repos we should ignore when sweeping bugs. For simplicity, the operator-related bugs are determined by a hardcoded list of bug components. Please have a look anyway.
> ART-997: Sweep (or don't sweep) bugs into correct advisory

- elliottlib/cli/__main__.py
- elliottlib/cli/common.py
- elliottlib/cli/verify_cvp_cli.py
- elliottlib/constants.py
- elliottlib/gitdata.py
- elliottlib/resultsdb.py
- elliottlib/util.py
- requirements.txt
Example: Verify CVP test results for all latest 4.4 image builds, also warn those with failed content_set_check
```sh
$ elliott --group openshift-4.4 verify-cvp --all --include-optional-check content_set_check
```
Example 2: Apply patches to ocp-build-data to fix the redundant content sets error:
```sh
$ elliott --group openshift-4.4 verify-cvp --all --include-optional-check content_set_check --fix
```
See https://issues.redhat.com/browse/ART-1981 for more info.
> Add 'verify-cvp' verb to verify CVP test results

- elliottlib/bzutil.py
- elliottlib/cli/__main__.py
- elliottlib/errata.py
- tests/test_bzutil.py
To enable a new workflow, `elliott` needs to be able to find `ON_QA` bugs which are not attached to advisories, and attach them. A limitation and/or configuration  of Errata Tool does not allow to attach an `ON_QA` bug. This PR sets the state of an eligible `ON_QA` bug to `MODIFIED` in order to attach it to an advisory.
**end-to-end verification**
`elliott repair-bugs` still works:
```
% bugzilla query --id 1850481
#1850481 CLOSED     - lmeyer@redhat.com - Placeholder bug for OCP 4.2.z metadata release
% elliott --group=openshift-4.2 repair-bugs --auto --use-default-advisory metadata --from CLOSED --to MODIFIED
2020-08-28 09:51:52,755 INFO Cloning config data from https://github.com/openshift/ocp-build-data.git
2020-08-28 09:51:54,328 INFO Using branch from group.yml: rhaos-4.2-rhel-7 …
```
> [ART-2057] find-bugs sweep includes `ON_QA` bugs

- Jenkinsfile
Tox does not detect changes in requirements, and will fail with missing
imports.
[example](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/art-tools/job/elliott/job/master/6/console)
[tox bug](https://github.com/tox-dev/tox/issues/149)
This PR looks at the files that have changed in the last 5 commits, and
if one of the files that might contain requirements have changed, will
add the argument `--recreate` to the `tox` invocation.
The magical number 5 was chosen, as it is conceivable that there are
multiple commits locally which contain the change, and the change in
dependencies is not detected.
Alternative approaches are:
- install a tox plugin
- always recreate in Jenkins
> Rebuild tox environment after change requirements

- elliottlib/cli/common.py
- elliottlib/cli/verify_cvp_cli.py
- elliottlib/resultsdb.py
- requirements.txt
This PR makes `elliott verify-cvp` smarter to analyze CVP content set test results and provide more automatic fixes.
Note `verify-cvp` is not fully production-ready and the code has not been fully tided up.
> Smarter CVP analysis

- elliottlib/errata.py
As a result of an [EXD ticket](https://projects.engineering.redhat.com/browse/CLOUDWF-3104), the Errata Tool product configuration has changed to include `ON_QA` bugs as permissable bug status when attaching to an advisory. The product configuration can be seen here: https://errata.devel.redhat.com/products/79.
This commit removes the workaround.
> find-builds: Stop setting ON_QA bugs to MODIFIED

- elliottlib/cli/__main__.py
- elliottlib/cli/common.py
- elliottlib/cli/verify_cvp_cli.py
- elliottlib/exectools.py
- requirements-dev.txt
- tests/test_exectools.py
We no longer (necessarily) rebuild and ship all images each week, which means part of the payload may not be new and won't be present in the advisory we ship. In this situation elliott verify-payload should not count shipped images as missing.
This PR also show images already attached to advisories (useful when preparing a release but the previous release is on the fly) and introduces asyncio to boost the performance.
Test run:
```sh
$ elliott --group=openshift-4.4 verify-payload registry.svc.ci.openshift.org/ocp/release:4.4.0-0.nightly-2020-08-29-033321 58631
{
"missing_in_advisory": {},
"payload_advisory_mismatch": {},
"in_other_adivosires": {
"ose-aws-machine-controllers-container": "ose-aws-machine-controllers-container-v4.4.0-202008210157.p0", …
```
> ART-2170: do not count shipped images as missing

- elliottlib/errata.py
Fix errors like
```bash
Error sweeping bugs (will retry a few times):
hudson.AbortException: failed shell command: elliott --group=openshift-3.11 find-...mode sweep --into-default-advisories
with rc=1 and output:
[...see full archive #6...]
python-requests-2.19.1-4.el7ost
ErrataException Message: Erratum 58675: idsfixed: Bug #1873466 The bug is filed already in RHBA-2020:3694.
, retry it again
ElliottFatalError("ErrataException('Erratum 58675: idsfixed: Bug #1873466 The bug is filed already in RHBA-2020:3694.\\n',)",)
```
> Fix bug sweep

- elliottlib/bzutil.py
- elliottlib/cli/create_placeholder_cli.py
See [ART-2297](https://issues.redhat.com/browse/ART-2297)
This commit stops hardcoding the placeholder version to `unspecified`. This was suddenly not accepted anymore. Instead, it loads the `version` data from `bugzilla.yml` in `ocp-build-data`.
Warning, the `version` field gets recycled.
At the moment, for all the active release branches in ocp-build-data, only openshift-3.11 uses `version` in `bugzilla.yml` to narrow down the results of the appropriate bugs. The result set is not really narrow, as all active versions from that time were listed here. The real filtering of bugs happens when selecting on `target_release`.
The `openshift-4.Y` branches do not have `version` specified in `bugzilla.yml`. The first commit in this PR enables the recycling, as it stops using the `version` filter …
> [ART-2297] placeholder version

- elliottlib/cli/__main__.py
- elliottlib/cli/advisory_drop_cli.py
- elliottlib/constants.py
Advisories can only be dropped by their creators, or by program
management. This change implements the advisory-drop command, which
allows a bot user that creates advisories, to also drop them.
> [ART-2287] Create advisory-drop command

- .devcontainer/dev.Dockerfile
- elliottlib/brew.py
- elliottlib/cli/__main__.py
- elliottlib/cli/verify_attached_operators_cli.py
- elliottlib/constants.py
Verify attached operator manifest references are shipping or already shipped.
Takes a list of advisories that may contain operator metadata/bundle builds or image builds that are shipping alongside. Then determines whether the operator manifests refer only to images that have shipped in the past or are shipping in these advisories. An error is raised if there are no manifest builds attached, or if any references are missing.
> [ART-1054] introduce verify-attached-operators

- elliottlib/cli/__main__.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata.py
- elliottlib/util.py
- functional_tests/test_advisory_images.py
- functional_tests/test_change_state.py
- functional_tests/test_find_builds.py
- functional_tests/test_verify_attached_bugs.py
validate that bugs in a release are also fixed in next minor version and that they target the right version in the first place.
also fixes up functional tests I found were broken. I implemented functional tests rather than unit tests as the main failure mode here is getting the API or API object attrs wrong.
> [ART-2196] introduce verify-attached-bugs

- .devcontainer/dev.Dockerfile
- .devcontainer/devcontainer.json
Pylance has replaced Microsoft Python Language Server as the recommended
Python language server for VSCode.
> Update dev container configs

- elliottlib/brew.py
- elliottlib/cli/__main__.py
- elliottlib/cli/get_golang_versions.py
- elliottlib/constants.py
- elliottlib/errata.py
- elliottlib/util.py
Adds a command that retrieves the root.log for brew builds and extracts the installed Go version. Potentially useful for tracing when the Go version has changed.
Example:
```
$ ./elliott get-golang-versions 60147
Fetching advisory builds: Advisory - 60147
Looping over tags: 2 tags to check
Looping over builds in tag: OSE-4.6-RHEL-8 with 5 builds
Looping over builds in tag: RHEL-7-OSE-4.6 with 2 builds
Found 5 builds
podman-1.9.3-3.rhaos4.6.el8: golang-1.15.0-1.module+el8.4.0+7995+d3ff3d9b.x86_64
Could not get root.log for jenkins-2-plugins-4.6.1601368321-1.el8
skopeo-1.1.1-2.rhaos4.6.el8: golang-1.14.4-2.module+el8.3.0+7324+24e3ded4.x86_64
runc-1.0.0-81.rhaos4.6.git5b757d4.el7: go-toolset-1.13-1.13.4-3.el7.x86_64
openshift-clients-4.6.0-202010081244.p0.git.3794.4743d24.el7: …
```
> Add get-golang-versions cli command

- elliottlib/cli/get_golang_versions.py
- elliottlib/errata.py
Before:
```
$ ./elliott get-golang-versions 66145
Fetching advisory builds: Advisory - 66145
Looping over tags: 2 tags to check
Looping over builds in tag: OSE-4.4-RHEL-8 with 3 builds
Looping over builds in tag: RHEL-7-OSE-4.4 with 6 builds
Found 7 builds
Could not get root.log for iptables-1.8.4-10.el8_2.4
openshift-4.4.0-202011130111.p0.git.0.4861dfa.el7: go-toolset-1.13.x86_64 0:1.13.15-1.el7
openshift-clients-4.4.0-202011122017.p0.git.3445.6937a03.el7: go-toolset-1.13.x86_64 0:1.13.15-1.el7
faq-0.0.6-5.el7: go-toolset-1.13.x86_64 0:1.13.15-1.el7
atomic-openshift-service-idler-4.4.0-202011122017.p0.git.15.d3ab88f.el7: go-toolset-1.13.x86_64 0:1.13.15-1.el7
atomic-enterprise-service-catalog-4.4.0-202011122017.p0.git.1806.53dc206.el7: go-toolset-1.13.x86_64 0:1.13.15-1.el7
Could not get …
```
> Fix bug in get-golang-versions which overlooked EL7/EL8 builds of the same package

- elliottlib/cli/get_golang_versions.py
- elliottlib/constants.py
- elliottlib/errata.py
Currently `get-golang-versions` command only works for RPMs. This PR adds support for container builds.
Example
```
$ ./elliott get-golang-versions 66146
atomic-openshift-descheduler-container:	openshift-golang-builder-container-v1.13.0-202011132013.el7
cluster-logging-operator-container:	openshift-golang-builder-container-v1.13.0-202011132013.el7
cluster-nfd-operator-container:	openshift-golang-builder-container-v1.13.0-202011132013.el7
ose-clusterresourceoverride-operator-container:	openshift-golang-builder-container-v1.13.0-202011132013.el7
ose-clusterresourceoverride-container:	openshift-golang-builder-container-v1.13.0-202011132013.el7
...
```
> Add container support to get-golang-versions

- elliottlib/cli/__main__.py
An example of output:
```sh
$ elliott -g openshift-4.5 verify-payload registry.svc.ci.openshift.org/ocp/release:4.5.0-0.nightly-2020-12-05-205859 66865
{
"missing_in_advisory": {},
"payload_advisory_mismatch": {},
"in_pending_advisory": [],
"in_shipped_advisory": [
{
"id": 57754,
"type": "RHBA",
"url": "https://errata.devel.redhat.com/57754",
"summary": "OpenShift Container Platform 4.5.5 bug fix update",
"state": "SHIPPED_LIVE",
"nvrs": [
"jenkins-agent-nodejs-8-rhel7-container-v4.5.0-202007301938.p0"
]
}
]
}
```
> ART-2305: verify-payload shows advisory info for missing builds

- elliottlib/brew.py
- elliottlib/cli/get_golang_versions.py
- elliottlib/util.py
Previously was failing on some root.logs that installed Go from RHEL8 modules
> Fix bug in parsing Go version from root.logs

- Makefile
- elliottlib/brew.py
- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_cli.py
- elliottlib/errata.py
**Summary**
- https://issues.redhat.com/browse/ART-2592
- This is a change to elliott find-bugs sweep functionality (see the full command below), to detect rpm cve tracker bugs and attach those to the rpm advisory
- The bugs are validated against brew builds attached to advisory. If builds are not found then bugs are not attached, so the ideal sweep workflow needed for this change would be sweep builds and then sweep bugs.
**Status**
- ~~Some unit tests~~ - No unit tests exist for find bugs - would do a follow up story after current refactoring see https://github.com/openshift/elliott/pull/177
**Testing:**
- `./elliott -g openshift-4.6 find-bugs --mode sweep --cve-trackers --into-default-advisories --check-builds --dry-run`
- `./elliott -g openshift-4.7 find-builds -k rpm` <- verify it …
> ART-2592 Attach RPM CVE tracker bugs to RPM advisory

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_cli.py
- https://issues.redhat.com/browse/ART-2445
- Previous PR https://github.com/openshift/aos-cd-jobs/pull/2519
This PR adds a new mode to find-bugs 'blocker', which looks up blocker bugs for a group. 
- By default cve trackers are included
- Also a new flag `--exclude-status` which lets you exclude bug status
- `./elliott -g openshift-4.7 find-bugs --mode blocker --report`
- `./elliott -g openshift-4.7 find-bugs --mode blocker --exclude-status ON_QA --report`
> ART-2445 Add find-bugs mode to check for blocker bugs

- elliottlib/attach_cve_flaws.py
- elliottlib/cli/verify_attached_bugs_cli.py
This change introduces the switch `verify-bug-status` to `elliott
verify_attached_bugs`. If specified, the advisory validation of bugs
will complain if a bug is not yet verified, or is closed with another
reason than `ERRATA`. This probably is a sign that the bug needs
dropping or verification.
> [ART-2801] Add --verify-bug-status to verify_attached_bugs

- .devcontainer/brewkoji.conf
It is not used in latest brew and broken on new brew installation.
> Deprecate legacy CA

- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/errata.py
This is a small modification for the attach bugs commands in elliott.
- `find-bugs --mode sweep`
- `attach-cve-flaws`
Now it shows exactly which bugs are new and not already attached to an advisory. It also happens in the --dry-run mode, so you can see what exactly will happen without actually running it.
There was no story for it, but I found this to be a feature I sorely needed to see what was actually changing in an advisory, when manually running those commands. This allows ARTists to run those commands with `--dry-run` and see what modification they would've made. Sometimes bugs are manually attached/dropped and reattaching old dropped bugs or new bugs unintentionally is problematic (more so in case of cve flaws in which case we have to get ProdSec to drop them).
Implementation-wise, …
> Show existing and new bugs when sweeping

- elliottlib/brew.py
- elliottlib/cli/find_builds_cli.py
- tests/test_brew.py
This is a change that will help us not sweep the latest builds for all packages, which will help us in scenarios like we faced today (april 5th) when preparing 4.6 advisories. Which was that we had nightlies for 4.6 already that we wanted to use. But before automation could be frozen, ocp4 job triggered and started building again, it build some packages and then failed for some. Brew outage also responsible for other failures. 
The point is even if we had all success builds, we would still want the option of using builds from a point of time in the past. And in cases like partial builds succeeding, this would be critical.
---
In order to sweep latest builds for a (tag, package) combo we need to give an event id (similar to a timestamp) to brew methods. Luckily the method we are using for …
> Sweep builds by brew event

- .devcontainer/dev.Dockerfile
- elliottlib/brew.py
- elliottlib/cli/common.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/cli/verify_attached_operators_cli.py
- elliottlib/runtime.py
- setup.py
- tests/test_find_builds_cli.py
- If assemblies feature is disabled, find-builds should keep the current
behavior (attaching latest builds in -candidate Brew tags).
- Running elliott, without an assembly parameter should only attach images/rpms to advisories if they have .assembly.stream or, if no .assembly.stream exists, then the latest build without .assembly in the RELEASE field.
- Running elliott with an assembly parameter should prefer builds with that assembly in the RELEASE field.
> ART-2927: find-builds basic assembly awareness

- elliottlib/cli/find_builds_cli.py
```
...
click.echo(f'Found {len(brew_latest_builds)} builds. Filtering out shipped builds...')
TypeError: object of type 'generator' has no len()
```
> find-builds: Fix exception in log output

- elliottlib/errata.py
When we prepare GA advisories, we attach bugs in numbers exceeding a thousand. Errata tool attaches bugs but fails on the part where it posts a single comment about all the bugs attached in a request. The single comment is huge and it exceeds the character limit defined. This is a change so that doesn't happen.
> [Sweep] Attach bugs in batches

- elliottlib/cli/attach_cve_flaws_cli.py
Reworking of https://github.com/openshift/elliott/pull/188 to use existing templating feature of ocp_build_data.
> ART-2718: When switching to RHSA set the appropriate Impact in the topic

- elliottlib/cli/find_builds_cli.py
Slurping a generator for a second time makes one inhale nothingness rather than
consume content. With this change, rpms will be attached to the advisory.
> Fix find-builds -k rpm

- elliottlib/attach_cve_flaws.py
- elliottlib/cli/attach_cve_flaws_cli.py
https://issues.redhat.com/browse/ART-3095
This is blocking us from preparing 4.8 GA advisories
Also removed advisory.dump() since it stupidly fails on a string concatenation error when there's no manager email (shaking my head..)
> ART-3095 Attach-cve-flaws shouldn't fail when there are no tracker bugs

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_cli.py
- setup.py
- tests/test_bzutil.py
According to @jupierce :
```
Let:
Z be a non-closed BZ in a monitored component
S2 be the current state (as in the moment we are scanning) of Z
S1 be the state of the Z at the moment of the basis
A be the set of state changes Z after the basis
F be the sweep states (MODIFIED, ON_QA, VERIFIED)
Then Z is swept in if all the following are true:
S1 ∈ F
S2 ∈ F
A | ∄v : v <= S1
In prose: if a BZ seems to qualify for a sweep currently and at the basis event, then all state changes after the basis event must be to a greater than the state which qualified the BZ at the basis event.
```
Note:
1. Because this PR is implemented before adding assembly lense to Elliott ([ART-3045](https://issues.redhat.com/browse/ART-3045)), the basis event in this PR is taken from the command line argument like …
> ART-3057: find-bugs basis Brew event awareness

- elliottlib/assembly.py
- elliottlib/cli/find_bugs_cli.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/runtime.py
- tests/test_assembly.py
- Copies assembly.py from https://github.com/openshift/doozer/pull/431.
- Loads group config from releases.yml
- Loads basis event from releases.yml
Note:
1. Computing cutoff timestamp from basis event in `find-bugs` is not covered.
2. Honoring `is` in `find-builds` is not covered.
3. I didn't introduce the global `--brew-event` option because Elliott doesn't have a global koji wrapper that injecting global event Id like Doozer. If we need that, we can introduce that in a separate PR.
4. Please also look at https://github.com/openshift/ocp-build-data/pull/979. It adds add -hotfix tag to Errata product version mapping. We need that mapping to attach builds.
> ART-3045: Assembly lense

- elliottlib/assembly.py
- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_cli.py
- elliottlib/runtime.py
- elliottlib/util.py
- tests/test_bzutil.py
- tests/test_util.py
Let:
- `t1` be the timestamp of basis Brew event;
- `t2` be the timestamp of sweep cutoff;
- `I` be the set of latest image builds in the stream assembly at the moment of the basis t1;
- `R` be the set of rpms builds in the stream assembly at the moment of the basis t1;
- `H(b)` is the timestamp in a component build's NVR.
Then:
`t2 = max( { H(i) | i ∈ (I ∪ R)  } )`
> Honor assembly.issues and calculate approximate sweep cutoff time from basis event

- elliottlib/cli/find_builds_cli.py
We don't want to include shipped builds. All builds for Errata should be
directly tagged into `-candidate` or `-hotfix` tags.
> Set inherit=False when sweeping rpms from tags

- elliottlib/cli/validate_rhsa.py
This caused elliott to exit on first Alert, rather than printing all alerts.
@vfreex @thegreyd
> fix indentation error

- elliottlib/util.py
- tests/test_util.py
Ported from https://github.com/openshift/doozer/pull/466
> Allow isolate_assembly to work with X.Y.Z and el suffixes

- elliottlib/attach_cve_flaws.py
- tests/test_attach_cve_flaws.py
While preparing GA I'm dry-running attach-cve-flaws, these 2 stood out
- missing whiteboard error is getting printed for bugs that don't belong - fix that
- it's important to know for which component a flaw bug is considered first-fix - so print that.
> First fix - filter out irrelevant bugs early and print component

- elliottlib/bzutil.py
So they can be excluded from reports.
> [ART-3175] Add "Automation" keyword to placeholder bugs

- elliottlib/runtime.py
The error message is like
```
ElliottFatalError('Cannot run with assembly basis event 40126984 and --brew-event at the same time.',)
```
This is because the runtime is double initialized after create verbs
calls `ctx.invoke`.
> Fix create verb crashes if the runtime assembly has a basis event

- requirements.txt
With python-bugzilla => 3.0.2, leaks of bugzilla api keys on Request
exceptions is mitigated. Enforce this as a minimum version.
> Prevent BZ api key leak

- elliottlib/cli/__main__.py
- elliottlib/cli/find_builds_cli.py
- tests/test_find_builds_cli.py
Currently Elliott build sweep excludes shipped builds by checking if a build has a tag that ends with `-released`.
However we noticed an exception when preparing 4.7.26.
This PR updates the `_find_shipped_builds` function to use a more
precise check.
> ART-3277: Fix a build sweep issue

- elliott
- elliottlib/bzutil.py
- elliottlib/cli/__main__.py
- elliottlib/cli/create_textonly_cli.py
Add create text only cli for elliott it create a custom advisory and along with a custom bug in create text only advisory use case, all required data for advisory and bug need pass from jenkins job's parameters since each cases are different.
> art-3078: Add create text only cli

- elliottlib/cli/__main__.py
- elliottlib/cli/advisory_commons_cli.py
I wanted a command to update the shipping date of a group of advisories without having to go through ET.
Made it a little general purpose so you can get any field across advisories, if you wanted to.
And then update common fields across advisories like date, manager, qe, owner etc. 
I don't see us updating the others as much
and date as basically the only real feature :) 
but worth it
> [Hack n Hustle] Get and update common fields across advisories

- elliottlib/bzutil.py
Since https://bugzilla.redhat.com/show_bug.cgi?id=2003517, bugzilla api returns maximum 20 bugs. This PR sets this limit to unlimited.
> Set bugzilla query limit to infinite

- elliottlib/gitdata.py
In case there is a substitution where no key is provided, leave it alone
> Fail if placeholder cannot get substituted

- elliottlib/cli/verify_attached_operators_cli.py
- elliottlib/exectools.py
- functional_tests/test_verify_attached_operators.py
- tests/test_verify_attached_operators.py
if an operator is missing, look up its NVR, not just its shasum
> verify_attached_ops: lookup bundle-referenced NVRs

- elliottlib/cli/tag_builds_cli.py
- elliottlib/metadata.py
- functional_tests/test_verify_attached_operators.py
- tests/test_metadata.py
- tests/test_structures.py
- tests/test_util.py
See https://github.com/openshift/doozer/pull/527.
There's no code in Elliott using the git commit hash. This PR just updates
comments and tests to keep consistency with Doozer.
> Use new git commit format in release field

- elliottlib/cli/verify_attached_bugs_cli.py
Introduced a new CLI command, `verify-bugs`, that is similar to `verify-attached-bugs`, but without the need of advisories. It receives a list of bug IDs as arguments.
To be able to verify potential regressions before we prepare release. With this new command, we can verify bugs that will be swept to advisories, before the advisories even exist.
The intention is to use this command inside a scheduled job, that will check for potential regressions once a day and inform us the findings on Slack, so we can be aware and alert people earlier in the process, in the hopes that issues will be addressed before Wednesday, and not delay promotions.
```
$ bugs="$(elliott -g openshift-4.9 find-bugs --mode sweep | tail -n1 | cut -d':' -f2 | tr -d ,)"
$ echo $bugs
1954309 1972082 1973585 1989798 1992744 …
```
> [ART-3383] Verify bugs not (yet) attached to advisories

- .gitignore
- Jenkinsfile
- elliottlib/cli/__main__.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/constants.py
- elliottlib/errata.py
- functional_tests/test_advisory_images.py
- functional_tests/test_change_state.py
- functional_tests/test_create.py
- functional_tests/test_find_bugs.py
- functional_tests/test_find_builds.py
- functional_tests/test_find_cve_trackers.py
- functional_tests/test_get.py
- functional_tests/test_list.py
- functional_tests/test_poll_signed.py
- functional_tests/test_rpmdiff.py
- functional_tests/test_tarball_sources.py
- functional_tests/test_verify_attached_bugs.py
- functional_tests/test_verify_payload.py
- tests/test_errata.py
- tox.ini
This commit:
- Refactors Errata by extending the Errata class from errata_tool. Some
common operations can now be executed on the advisory itself.
- Gets some testing in place for common advisory actions
- Calls `advisory.commit()` once, and not for each Product Version
- Changes the state of the advisory to NEW_FILES when builds need to get
attached and the advisory is not in that state
> [ART-3400] find-builds: Change advisory state only when needed

- elliottlib/util.py
This helps for advisories for products like openshift serverless, e.g. 
```
$ ./elliott go -a 79064
Following nvrs are built with N/A:
openshift-serverless-1-kn-cli-artifacts-rhel8-container-0.23.2-1
openshift-serverless-1-must-gather-rhel8-container-1.17.0-5
openshift-serverless-1-serverless-operator-bundle-container-1.17.0-11
Following nvrs are built with go-toolset-container-1.15.14-3:
openshift-serverless-1-client-kn-rhel8-container-0.23.2-2
openshift-serverless-1-eventing-apiserver-receive-adapter-rhel8-container-0.23.0-5
openshift-serverless-1-eventing-controller-rhel8-container-0.23.0-5
openshift-serverless-1-eventing-in-memory-channel-controller-rhel8-container-0.23.0-5
openshift-serverless-1-eventing-in-memory-channel-dispatcher-rhel8-container-0.23.0-5 …
```
> Check go version in containers named "go-toolset"

- elliottlib/assembly.py
- elliottlib/cli/rhcos_cli.py
- elliottlib/util.py
Summary:
This expands the elliott rhcos command to support nightly and assemblies lookup. 
Assembly lookup is useful when the release hasn't been promoted, and we want to verify some package.
Also removes latest and latest_ocp options - since they weren't essential to the command nor had enough utility to keep supporting the complexity they bring
Test
- `elliott -g openshift-4.9 rhcos -r 4.9.0-0.nightly-arm64-2021-12-20-082621 -p selinux-policy`
- `elliott -g openshift-4.9 --assembly 4.9.8 rhcos -p selinux-policy`
> [rhcos] Support nightly and assembly

- elliottlib/cli/find_bugs_cli.py
- elliottlib/constants.py
- elliottlib/errata.py
With current size of 500, still see bugzilla timing out - 
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/227/console
> Reduce bug lookup batch size

- requirements.txt
Soon, Authentication will change for bugzilla. Release 3.2.0 of
python-bugzilla accomodates for this change by removing cookiefile
support and adding an `Authorization: Bearer <blurp>` to the request
headers.
Target Dates:
dev: Mon 17th Jan 00:00 UTC (Completed)
qa: Mon 31st Jan 00:00 UTC
stage: Mon 07th Feb 00:00 UTC
prod: Mon 28th Feb 00:00 UTC
From https://mailman-int.corp.redhat.com/archives/bugzilla-list/2022-January/msg00004.html
> Ensure 3.2+ is used for python-bugzilla

- elliottlib/bzutil.py
and interactive login is disabled
> [ART-3790] Exit with error code 1 if no BZ credentials are found

- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata_async.py
- The Errata server doesn't seem to support keep-alive. Using `force_close=True` option to solve the `aiohttp.client_exceptions.ServerDisconnectedError`.
- Exit with non-zero if `--verify-flaws` finds any issues.
> verify-attached-bugs: Fix some --verify-flaws issues

- elliottlib/cli/verify_attached_bugs_cli.py
Fix error message like
```
Couldn't determine target release for attached trackers: Found different target_release values for tracker bugs: set(). There should be only 1 target release for all bugs. Fix the offending bug(s) and try again.
Some bug problems were listed above. Please investigate.
```
That error comes from current_target_release, err = util.get_target_release(attached_trackers) . The function raises an error if attached_trackers is empty array/set.
> verify-attached-bugs: fix flaw bugs check issue when no trackers are attached

- elliottlib/cli/find_bugs_cli.py
Current formatting does not pretty print URLs to Slack channels; this PR applies <url|link text> format instead.
See https://github.com/openshift/doozer/blob/master/doozerlib/cli/images_health.py#L51 for details
> Apply slack formatting to URL

- elliottlib/cli/verify_attached_bugs_cli.py
The signature of constructor for `class BugValidator` was changed by 5df92dd0bc3728a07c4172dff6966ffd76637b97
Fixes
```
File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/elliott/elliott", line 11, in <module>
main()
File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/elliott/elliottlib/cli/__main__.py", line 737, in main
cli(obj={})
File "/home/jenkins/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/home/jenkins/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/home/jenkins/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
return …
```
> verify-attached-bugs: Fix TypeError

- elliottlib/bzutil.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/exectools.py
- elliottlib/metadata.py
- elliottlib/runtime.py
- requirements.txt
- tests/test_metadata.py
- Sync get_latest_build and brew wrapper related code from doozerlib.
- Call get_latest_build in parallel. This will significantly improve the
performance for commands like `find-builds` and `find-bugs`.
> Consolidate get_latest_build and call it in parallel

- elliottlib/cli/get_golang_versions_cli.py
- elliottlib/errata_async.py
- elliottlib/rpm_utils.py
- requirements.txt
This package is RHEL-only, which also caused a lot of build failures in
the past.
It doesn't seem to be actually used in Elliott.
> Remove rpm-py-installer

- Makefile
- elliottlib/bzutil.py
- elliottlib/cli/cli_opts.py
- elliottlib/cli/find_bugs_cli.py
- requirements.txt
- tests/test_find_bugs_cli.py
Test:
- Set your JIRA_TOKEN and `export https_proxy=http://squid.corp.redhat.com:3128`
- elliott -g openshift-4.11 find-bugs --mode list --id OCPBUGS-10 --jira -o text --report
- elliott -g openshift-4.11 find-bugs --mode list --id OCPBUGS-10 --jira -o json --report
- elliott -g openshift-4.11 find-bugs --mode list --id OCPBUGS-10 --jira -o slack --report
```json
[
{
"id": "OCPBUGS-10",
"component": "OLM/OperatorHub",
"status": "New",
"date": "2022-03-23 19:49:49+00:00",
"summary": "[2034409] Default CatalogSources should be pointing to 4.10 ",
"url": "https://issues.stage.redhat.com/browse/OCPBUGS-10"
}
]
```
> find-bugs list mode report can use jira

- elliottlib/bzutil.py
Running create-placeholder got the following error:
```
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/create_placeholder_cli.py", line 60, in create_placeholder_cli
newbug = elliottlib.bzutil.BugzillaBugTracker(bz_config).create_placeholder(kind)
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/bzutil.py", line 319, in create_placeholder
return self.create_bug(boilerplate, boilerplate, "VERIFIED", ["Automation"])
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/bzutil.py", line 309, in create_bug
return BugzillaBug(new_bug)
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/bzutil.py", …
```
> Fix AttributeError: Bug object has no attribute 'target_release'

- elliottlib/cli/find_bugs_sweep_cli.py
although we query the sub_component fields in search, it still may not exist
`If 'sub_component' is a bugzilla attribute, it may not have been cached when the bug was fetched. You may want to adjust your include_fields for getbug/query.`
> fix sub_component check

- requirements.txt
Pin of pygit2 is necessary on rhel7 / python3.6, but breaks elliott on
fedora 36. This change makes elliott runnable on both.
> Enable elliott in F36

- elliottlib/cli/common.py
the brew API won't accept it as a string.
`koji.GenericError: Invalid event: '45837595'`
> cli/common: make brew-event an int

- tests/test_find_bugs_qe_cli.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_remove_bugs_cli.py
- tests/test_repair_bugs_cli.py
Unit tests have been failing due to `USEJIRA` env var being set,
and then failing to be unset. Instead of directly setting and unsetting
os.environ, we use patch decorator in tests requiring the var, which is safer.
I've also consolidated test cases in test_find_bugs_sweep_cli - we used to 
have test cases for only bugzilla, and only jira. Instead now we have each 
test case using bugzilla and jira in one (not all but most relevant of them)
Test
- Run `make test` from project repo
> Fix failing unit tests

- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- requirements.txt
- tests/test_attach_cve_flaws.py
Branched off of https://github.com/openshift/elliott/pull/350 (Ignore those changes)
Includes several fixes
- Fix is_flaw_bug and is_tracker_bug methods for jira
- Include tracker_type str attr in bug_tracker for logging
- Abstract out advisory_bug_ids method in bug_tracker (needs upgraded errata-tool package)
- Remove check_tracker param in get_bugs (imo an anti-pattern we should avoid)
- Remove kwargs where not needed in fetch methods (they were breaking search)
- Don't use exit(0) in func runs
Test
- `elliott -g openshift-4.10 --assembly rc.1 attach-cve-flaws --noop --use-default-advisory image`
- With jira 
- `export JIRA_TOKEN=<token>`
- `USEJIRA=True` and run ^^ again
> Fixes to attach-cve-flaws w/ jira

- elliottlib/bzutil.py
- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/errata.py
- tests/test_remove_bugs_cli.py
Note: errata api for removing jira bugs is broken. I'll follow up with the team
Summary
- Make sure bug id given is attached to the advisory
- Abstract out out bug remove logic into bug tracker methods
- Change the cli interface (no longer `--id`) to be consistent with attach-bugs
Test
- `make test`
- `elliott -g openshift-4.10 --assembly 4.10.19 remove-bugs --all --use-default-advisory image --noop`
- `elliott -g openshift-4.10 --assembly 4.10.19 remove-bugs 2095114 --use-default-advisory image --noop`
- `USEJIRA=True ./elliott -g openshift-4.10 remove-bugs --advisory 96435 OCPBUGS-1`
> remove-bugs fixes

- requirements.txt
Multi-value flags broken in version 8.1.3 (which is the current latest).
```python
File "/home/ashwindas/.local/lib/python3.9/site-packages/click/core.py", line 2584, in __init__
raise TypeError("'multiple' is not valid with 'is_flag', use 'count'.")
TypeError: 'multiple' is not valid with 'is_flag', use 'count'.
```
Issue PR: https://github.com/pallets/click/issues/2292
> lock click version at 8.1.2

- elliottlib/util.py
- requirements.txt
elliott determines version from configured Product Versions, adding ironic's PV in the mix requires an update.
> util.py: update product version assumptions

- elliottlib/__init__.py
Command was failing when executed from outside Elliott folder. Setting root param for setuptools_scm.get_version() fixed it.
> Fix elliott --version

- elliottlib/bzutil.py
Test:
`elliott --group=openshift-4.11 attach-cve-flaws --advisory=97035 --noop`
```
...
Some bugs could not be fetched (1): {2092917}
```
> Print missing bugs when fetching bugs

- elliottlib/bzutil.py
- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/cli/find_bugs_blocker_cli.py
- elliottlib/cli/find_bugs_qe_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/runtime.py
- tests/test_find_bugs_qe_cli.py
- tests/test_remove_bugs_cli.py
Note: I'm breaking changes in this PR into several self-contained ones. After those merge, this should be the PR which has only 'onlyjira' changes
- https://github.com/openshift/elliott/pull/350
- https://github.com/openshift/elliott/pull/351
- https://github.com/openshift/elliott/pull/352
- https://github.com/openshift/elliott/pull/354
- https://github.com/openshift/elliott/pull/353
We want 3 modes when working with jira and bugzilla
1) Strictly use bugzilla only
- This is activated when no env var from USEJIRA/ONLYJIRA is set=True
2) Use jira and bugzilla in combo - whichever makes sense however. This is our auto mode, where we figure out how to use both of them in combination. Stuff where it doesn't make sense to use both like creating a bug, removing/repairing bugs - where we need to …
> Enable onlyjira mode for testing

- elliottlib/cli/find_bugs_sweep_cli.py
With the addition of new images on 4.10 (ART-4052, ART-4074, ART-4075, and ART-4076) we also need to sweep their corresponding bugs into advisories.
> Sweep TALM && BMER Bugs

- elliottlib/cli/find_bugs_sweep_cli.py
Throw an error when there are CVE tracker bugs that cannot get attached
because the component that they are about is not getting shipped.
Currently an event like this will go unnoticed, as the log is not
scrutinized.
The can be bypassed by either fixing the issue, or by exclkuding the
relevant bugs from the assembly:
`releases.<name>.issues.exclude: [1234]`
> Halt if rpm CVEs don't have corresponding build

- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/common.py
- elliottlib/cli/create_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata.py
- tests/test_attach_cve_flaws.py
- tests/test_attach_cve_flaws_cli.py
- tests/test_bzutil.py
Test jira flaw bug with custom flaw label: https://issues.redhat.com/browse/OCPBUGS-8
Test:
`USEJIRA=true ./elliott -g openshift-4.8 attach-cve-flaws -a 96435 --noop`
Right now jira issues are removed when updating an advisory through errata-tool
https://coreos.slack.com/archives/GDBRP5YJH/p1658947821887479
Fix https://github.com/red-hat-storage/errata-tool/pull/231 
I would want to continue with this PR and address this in a follow up PR
> Attach cve flaws with jira trackers and bugzilla flaws

- elliottlib/cli/common.py
```
Python 3.6.15
>>> import asyncio
>>> async def hello():
...   print("Hello")
>>> asyncio.run(hello())
File "<stdin>", line 1, in <module>
AttributeError: module 'asyncio' has no attribute 'run'
>>> asyncio.get_event_loop().run_until_complete(hello())
Hello
```
> Fix wrong function call on asyncio

- elliottlib/cli/attach_cve_flaws_cli.py
```
Python 3.6.15
>>> import asyncio
>>> async def hello():
...   print("Hello")
>>> asyncio.create_task(hello())
File "<stdin>", line 1, in <module>
AttributeError: module 'asyncio' has no attribute 'create_task'
>>> asyncio.get_event_loop().create_task(hello())
<Task pending coro=<hello() running at <stdin>:1>>
```
> Fix another wrong function call to asyncio

- elliottlib/cli/attach_cve_flaws_cli.py
```
Python 3.6.15
>>> flaw_bug_tracker = None
>>> flaw_bug_tracker.type
File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'type'
>>> flaw_bug_tracker.type if hasattr(flaw_bug_tracker, 'type') else ''
''
```
> Fix bug when flaw_bug_tracker is None (on attach_cve_flaws)

- requirements.txt
We need https://github.com/red-hat-storage/errata-tool/pull/231
for elliott working correctly.
The official errata-tool package release isn't cut yet,
I don't think we need to wait for that.
> Use latest errata-tool package with fix

- requirements.txt
Fix
```
error in rh-elliott setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'+ssh://g'": Expected stringEnd
```
> Fix requirments.txt and CI

- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/common.py
This is mostly for release artists running manually.
`elliott --assembly=4.11.0 --group=openshift-4.11 attach-cve-flaws --into-default-advisories --noop`
> Run attach-cve-flaws for all advisores for an assembly

- elliottlib/cli/change_state_cli.py
- elliottlib/errata.py
change-state should allow to change states from REL_PREP and back
Since release artists are not the only one using elliott
This will allow members of exd, rcm also use elliott
> Allow change-state to work with different states

- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/cli/find_bugs_blocker_cli.py
- elliottlib/cli/find_bugs_qe_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/repair_bugs_cli.py
- elliottlib/runtime.py
- tests/test_find_bugs_blocker_cli.py
- tests/test_find_bugs_qe_cli.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_remove_bugs_cli.py
- tests/test_repair_bugs_cli.py
Make usejira=True by default, so when we run elliott with no arguments/env vars
we will be using jira and bugzilla both by default in find commands (find-bugs and attach-cve-flaws)
Deprecate `ONLYJIRA` since it's creating confusion due to some commands only being able to run
in both bugzilla and jira mode, so supporting this is not guaranteed.
For commands which accept bug ids (attach-bugs, remove-bugs, repair-bugs, verify-bugs)
- To use Bugzilla ids with them `USEJIRA=0` or `USEJIRA=False`
> Make use_jira default true

- elliottlib/bzutil.py
- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/repair_bugs_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_remove_bugs_cli.py
- tests/test_repair_bugs_cli.py
This change is for elliott commands that accept bug_ids as argument. 
Right now we need usejira=True to tell elliott that we are passing in 
jira ids and usejira=False to tell those are bugzilla ids. With this change
we try to be smart and automatically recognize bug_ids into jira and bz
and run accordingly. If pattern matching on bugids fails we crash.
Note: verify-bugs needs a refactor and will need follow up work before
having this change in.
- `make test`
- `elliott -g openshift-4.9 attach-bugs [OCPBUGS-1](https://issues.redhat.com//browse/OCPBUGS-1) 2053222 -a 100250 --noop`
- `elliott -g openshift-4.9 remove-bugs [OCPBUGS-1](https://issues.redhat.com//browse/OCPBUGS-1) 2053222 -a 100250 --noop`
> Commands can recognize different bugids

- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_verify_attached_bugs_cli.py
validate two types of bugs together, if not usejira the related bug list would be empty, so when checking ET type it can compute result together
```
elliott --assembly 4.10.28 --group=openshift-4.10 verify-attached-bugs --verify-flaws
2022-08-24 09:46:28,861 INFO Cloning config data from https://github.com/openshift/ocp-build-data.git
2022-08-24 09:46:30,627 INFO Using branch from group.yml: rhaos-4.10-rhel-8
2022-08-24 09:46:30,627 WARNING Constraining brew event to assembly basis for 4.10.28: 46763830
Retrieving bugs for advisory [100251, 100250, 100252, 100249]
Verify blocking bugs for 2112995 Passed
Verify blocking bugs for 2104454 Passed
Verify blocking bugs for 2100369 Passed
Verify blocking bugs for 2110963 Passed
Verify blocking bugs for 2115267 Passed
Verify blocking bugs for …
```
> exclude placeholder bug in bug sweep and fix RHSA check

- elliottlib/bzutil.py
in bug https://bugzilla.redhat.com/show_bug.cgi?id=2105528 component name is `component:elasticsearch-operator-container, log-storage` 
it will treat it as a rpm bug
> component can have multi item

- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/constants.py
- elliottlib/errata_async.py
- tests/test_errata_async.py
This commit is an incomplete step towards ART-4552. `elliott
attach-cve-flaws` will now:
- error when mapping of builds to CVEs could not be made
- leave golang bumps to match the whole advisory
In case this runs into an error because the tracker is attached to the
wrong advisory, the tracker needs to be moved manually, and the process
repeated.
> Improve handling of CVE associations

- elliottlib/cli/__main__.py
```console
$  elliott -q -g openshift-4.10 --assembly 4.10.31 get --use-default-advisory extras --json - | jq -r '[.bugs[], .jira_issues[]]'
[
2091213,
2102672,
"OCPBUGS-502",
"OCPBUGS-503"
]
```
> Add jira trackers to get output

- elliottlib/bzutil.py
https://coreos.slack.com/archives/GDBRP5YJH/p1662540699647459
https://github.com/python-bugzilla/python-bugzilla/blob/main/bugzilla/base.py#L321
The bugzilla api expects "sub_components" to get the field
"sub_component"
> Bugzilla query search sub_component field fix

- elliottlib/cli/verify_attached_operators_cli.py
This change ensures that verify-attached-operators does not fail if there are no bundle images attached. Also, it will look if a build is attached to an advisory if it is not shipped yet, and if so, it will assume that it will ship.
> Fix verify operators

- .devcontainer/dev.Dockerfile
- elliottlib/__init__.py
- elliottlib/bzutil.py
- elliottlib/cli/verify_attached_bugs_cli.py
- requirements-dev.txt
- requirements.txt
Blocking bug check is not needed if the next minor version is GA'd.
Adding an option `--no-verify-blocking-bugs` to skip blocking check. This option will be used by
pyartcd.
Also bumps some dependencies and updates dev container Dockerfile for
python 3.8.
> verify-attached-bugs: add option to skip blocking bug check

- elliottlib/cli/attach_cve_flaws_cli.py
- tests/test_attach_cve_flaws_cli.py
If a flaw bug is dropped from the advisory, it should also be removed from the CVENames field of that advisory.
> attach-cve-flaws should remove CVEs if flaws are dropped

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_verify_attached_bugs_cli.py
Right now we rely on parsing the output of 
find-bugs:sweep to pass it on to verify-bugs
in our [check-bugs job](https://github.com/openshift/aos-cd-jobs/blob/master/pyartcd/pyartcd/pipelines/check_bugs.py).
Now with jira and bugzilla having different output - 
it makes more sense to make this into a native 
functionality.
```
elliott --group=openshift-4.10 --assembly=stream verify-bugs
```
Test run
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/hack/job/sidsharm-aos-cd-jobs/job/build%252Fcheck-bugs/8/console
> Verify-bugs --assembly=stream

- elliottlib/cvp.py
- requirements.txt
- Build logs of ovn-kubernetes-microshift image have lines like
```
2022-09-13 20:43:32,770 - atomic_reactor.plugins.imagebuilder - INFO -  openvswitch2.17                    x86_64  2.17.0-22.el8fdp  rhel-8-server-ose-rpms-embargoed-x86_64   16 M
2022-09-13 20:43:32,770 - atomic_reactor.plugins.imagebuilder - INFO -  python3-openvswitch2.17            x86_64  2.17.0-22.el8fdp  rhel-8-server-ose-rpms-embargoed-x86_64  238 k
```
We need to update the regex to allow package name to include a dot.
- OSBS 2 changed its logger name. Needs to update regex to match logs like
```
2022-09-22 22:22:24,813 - atomic_reactor.tasks.binary_container_build - INFO -  openvswitch2.17                    x86_64  2.17.0-22.el8fdp  rhel-8-server-ose-rpms-embargoed-x86_64   16 M
2022-09-22 22:22:24,813 - …
```
> verify-cvp: OSBS 2 accommodation and regex fix

- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/common.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata.py
- elliottlib/runtime.py
- tests/test_bzutil.py
- tests/test_bzutil_jira.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_verify_attached_bugs_cli.py
[https://issues.redhat.com/browse/ART-3380](https://issues.redhat.com/browse/ART-3380)
This affects sweep and verify-attached-bugs, to rely on
bug sorting for cve tracker bugs, based on attached builds.
--check-builds will become default and deprecate, so 
we'll always skip attaching trackers if builds are not found
Test
- `elliott --assembly=4.9.48 --group=openshift-4.9 verify-attached-bugs --verify-flaws`
> ART-3380 Improve Tracker Bug sorting

- elliottlib/bzutil.py
Following the
[announcement](https://groups.google.com/a/redhat.com/g/aos-devel/c/0j22YV-18no)  that bugs of high enough priority/severity, Release Blocker gets set to Proposed automatically. We should stop alerting on this.
> Do not trigger on Proposed Blockers

- elliottlib/cvp.py
There can be a `.` in the size.
> verify-cvp: Fix regex and reduce "not found" message

- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata_async.py
- tests/test_assertion.py
- tests/test_errata_async.py
- tests/test_pushd.py
- tests/test_verify_attached_bugs_cli.py
the previous ut has the following warning
```...............................................BZ 9 is ignored because its status was MODIFIED at the moment of sweep cutoff (2021-06-30 12:30:00), however its status changed back to ['ASSIGNED'] afterwards
...................No flaw bugs could be found for these trackers: {'OCPBUGS-2'}
...changed 123 from status1 to status2
.123 is already on status1
.changed 123 from status1 to status2
..changed 123 from status1 to status2
.123 is already on status1
.changed 123 from status1 to status2
................../mnt/workspace/jenkins/working/art-tools_elliott_PR-439/.tox/py38/lib64/python3.8/site-packages/aiohttp/connector.py:767: DeprecationWarning: The object should be created within an async function
super().__init__( …
```
> fix ut warning

- elliottlib/bzutil.py
- tests/test_bzutil.py
This should follow the spec: Order by Impact, then order by int.
> Sort CVEs better

- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/errata_async.py
the close function has been removed, no need to close it now
> fix error in attach-cve-flaws function

- elliottlib/bzutil.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_bzutil.py
- tests/test_verify_attached_bugs_cli.py
https://issues.redhat.com/browse/ART-4875
Test
- Test 4.6 Bug with jira and bz blocker https://issues.redhat.com/browse/OCPBUGS-8
- `./elliott --debug --assembly=stream --group=openshift-4.6 verify-bugs`
- Look for `DEBUG Candidate Blocker bugs found: ['OCPBUGS-1', 1826920, ...]`
> ART 4875 Use new jira field "blocked by bugzilla" to check regressions

- elliottlib/errata_async.py
- tests/test_errata_async.py
elliott verify-attached-bugs will raise such an error message
```
On advisory 103179, CVE-2022-30322 is associated with Brew components openshift-enterprise-cli-alt-container, ose-insights-operator-container without a tracker bug. You may need to explicitly exclude those Brew components from the CVE mapping or attach the corresponding tracker bugs.
On advisory 103179, CVE-2022-30323 is associated with Brew components kuryr-controller-container, ose-azure-disk-csi-driver-container without a tracker bug. You may need to explicitly exclude those Brew components from the CVE mapping or attach the corresponding tracker bugs.
On advisory 103179, CVE-2022-26945 is associated with Brew components cluster-monitoring-operator-container, ose-network-metrics-daemon-container without a tracker bug. …
```
> [RHELWF-7726] increase page size to 1000

- elliottlib/cli/verify_cvp_cli.py
Solving this issue:
```
File "/mnt/workspace/jenkins/working/aos-cd-builds_build_review-cvp@6/art-tools/elliott/elliottlib/cli/verify_cvp_cli.py", line 73, in verify_cvp_cli
del b["_tags"]  # b["_tags"] is of type set, which cannot be dumped into json or yaml
KeyError: '_tags'
```
> Fix error in cvp checker

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_assertion.py
- tests/test_bzutil.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_verify_attached_bugs_cli.py
ref: [ART-4877](https://issues.redhat.com//browse/ART-4877)
if a bug was backported to Jira, it might miss CVE-related labels but it has CVE feature in its summary and described in its description, so add a check to raise concern if we find such a mismatch in summary, it can be a filter that effect bug sweep and bug validate
> [ART-4877] Complain when Tracker Bugs don't have Tracker Keywords

- elliottlib/cli/verify_attached_operators_cli.py
in verify-attached-operators cli the output looks like
```
Some references were missing:
ose-ghostunnel@sha256:09eaea8f5269770839ed13958fe4ff7ee7e4aecf5f41e1c8bee4fcb2047c2961
ose-metering-hive@sha256:98101bf62a4afdb89985158fce21c347fbf844e0c73538121e009ef3a1bad4b9
ose-metering-reporting-operator@sha256:2d908913e3309d18b7ea63184c77d491c98ec84c57d5fa37a1a014719bd3c43a
ose-descheduler@sha256:c0fe8830f8fdcbe8e6d69b90f106d11086c67248fa484a013d410266327a4aed
Ensure all manifest references are shipped or shipping.
```
change the shasum to nvr for better readability
> verify-attached-operators print nvr for better readability

- elliottlib/metadata.py
Valid modes are `enabled`, `disabled`, and `wip`.
> Fix metadata mode check

- elliottlib/cli/find_builds_cli.py
add a flag to the `fild-builds` cli that can ignore already shipped builds and attach all builds to advisory
> add allbuilds flag

- elliottlib/cli/__main__.py
- elliottlib/rhcos.py
We want to skip rhel-coreos and rhel-coreos-extensions images
in verify-payload so it doesn't fail.
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/551/consoleFull
Test:
`elliott --group=openshift-4.12 --assembly rc.0 verify-payload registry.ci.openshift.org/ocp-arm64/release-arm64:4.12.0-0.nightly-arm64-2022-11-10-033917 104601`
> Skip rhcos images in verify-payload

- Makefile
- elliottlib/bzutil.py
- elliottlib/cli/verify_attached_bugs_cli.py
We can have a case where a non flaw bug can be attached to multiple advisories
```
curl -sSL --negotiate --user : https://errata.devel.redhat.com/jira_issues/OCPBUGS-35
71/advisories.json | jq -r '.[].advisory_name'
```
Verify that's not the case. Placeholder bugs are excluded so they are not included in this check,
so you won't see the above bug as a complain, but this should catch any other bugs.
Test
- elliott -g openshift-4.11 verify-attached-bugs 105365 --no-verify-blocking-bugs
> Verify bugs are not attached to multiple advisories

- elliottlib/errata.py
the first commit's exception didn't close, the exception will be raised in the second commit, like in the following example, the advisory object already raised an exception in the first commit, it will re-raised in the second commit
It can be solved by recreate Erratum object
```
>>> advisory = Erratum(errata_id=105587)
>>> advisory.addJiraIssues(['OCPBUGS-754'])
>>> advisory.commit()
File "<stdin>", line 1, in <module>
File "/Users/ximhan/Library/Python/3.9/lib/python/site-packages/errata_tool/erratum.py", line 954, in commit
self._write()
File "/Users/ximhan/Library/Python/3.9/lib/python/site-packages/errata_tool/erratum.py", line 913, in _write
self._processResponse(r)
File "/Users/ximhan/Library/Python/3.9/lib/python/site-packages/errata_tool/connecto …
```
> fix advisory exception

- elliottlib/bzutil.py
Component and subcomponent info does not match reality. We should not sweep assisted-installer bugs into OCP advisories. As there are only two more bugs that potentially will be swept, hard code a hack in the deprecated class.
Before:
```
$ elliott -g openshift-4.11 find-bugs:sweep --dry-run
...
2022-11-24 17:36:45,659 INFO Tracker Bugs found: 2
2022-11-24 17:36:45,659 INFO (2067863, 'ose-multus-admission-controller-container')
2022-11-24 17:36:45,659 INFO (2068230, 'assisted-installer-container')
```
After, 2068230 is not found.
> Ignore component:assisted-installer-container bugs

- elliottlib/brew.py
- elliottlib/cli/__main__.py
- elliottlib/cli/add_metadata_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/cli/list_cli.py
- elliottlib/cli/puddle_advisories_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/validate_rhsa.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/cli/verify_attached_operators_cli.py
- elliottlib/errata.py
- elliottlib/rpmdiff.py
- elliottlib/util.py
- requirements.txt
- tests/test_brew.py
`requests-gssapi` is used by koji and errata_tool packages internally, and it works on macOS.
> Migrate from requests_kerberos to requests-gssapi

- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata_async.py
- requirements-dev.txt
- tests/test_errata_async.py
- tests/test_exectools.py
- tests/test_verify_attached_bugs_cli.py
Probably due to https://github.com/openshift/elliott/pull/441, we occasionally get this exception while promoting a release:
```
ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```
This happened systematically while promoting a new RC, a task that usually involves sending multiple asynchronous requests to the Errata API. By leaving the client session open during the CLI execution, we should not incur into these server side errors anymore.
> Make client session a BugValidator instance attribute

- elliottlib/bzutil.py
Right now if there's a target release mismatch, the error
doesn't show the info to find the offending bug. This does that
./elliott --assembly=rc.4 --group=openshift-4.12 attach-cve-flaws --advisory 104601 --noop
> Better error for target release mismatch

- elliottlib/errata_async.py
The error message right now doesn't say what exactly
is wrong and how to fix it - let's do that.
> [verify-attached-flaws] Better error message for CVE names mismatch

- elliottlib/cli/verify_attached_bugs_cli.py
Multiple advisories check can be very slow, example
for GA advisories which can have ~1000 bugs, it can 
take upto 10 or more minutes. Provide a flag to skip it
> [verify-attached-bugs] Flag to skip multiple advisories check

- elliottlib/cli/rhcos_cli.py
- elliottlib/rhcos.py
Based on the doozer adjustment for unified builds https://github.com/openshift/doozer/pull/691/files
Test:
`elliott -g openshift-4.11 rhcos --release 4.11.0-0.nightly-2022-12-07-113128 -p kernel`
> rhcos - Fix for multi builds

- elliottlib/rhcos.py
On latest versions of oc, this is causing the command to error out
on warning. Let's not do that, if the cmd fails, an exception will be
raised by cmd_assert which should alert us on actual failure.
with a new oc client (4.11.18)
`elliott -g openshift-4.12 rhcos --release 4.12.0-0.nightly-2022-12-20-034740 -p kernel`
> rhcos - Do not error out on oc warning

- elliottlib/util.py
Ref. https://issues.redhat.com/browse/ART-5752
> Suppress output for images with no golang builder in their parents

- elliottlib/cli/find_bugs_sweep_cli.py
This kind of advisory doesn't exist prior to 4.12. Needs to skip if it doesn't exist in a release.
> find-bugs: Fix KeyError: 'microshift'

- elliottlib/bzutil.py
- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/errata.py
- tests/test_find_bugs_sweep_cli.py
I noticed when working with GA advisories - some commands
were taking a lot of time. In cases when we want to attach bugs
we were refetching the advisory in the attach method. Instead 
have an advisory_obj param and use that if we have advisory fetched.
> Reuse advisory object instead of refetching it 

- elliottlib/cli/get_golang_versions_cli.py
as we are tying to integrate `elliott go` cli into art-bot, we need to check the input value and return clear output
```
$ ./elliott go -a 00000000
The input value is not valid.
```
```
$ ./elliott go -a ""
Usage: elliott go [OPTIONS]
Try 'elliott go -h' for help.
Error: Invalid value for '--advisory' / '-a': '' is not a valid integer.
```
```
$ ./elliott go -a 111
there is no builds related to golang
```
> input value check for elliott go cli

- .devcontainer/devcontainer.json
- Makefile
- requirements-dev.txt
- tox.ini
according to https://app.snyk.io/org/openshift-art-build-bot/import-log/latest snyk require requirement-dev.txt follow the syntax that pkg should be in a list
test passed with
```
$./snyk test --file=requirements-dev.txt --package-manager=pip --command=python3
Testing ./ximhan/elliott...
Tested 76 dependencies for known issues, found 16 issues, 39 vulnerable paths.
Issues to fix by upgrading dependencies:
Upgrade future@0.18.2 to future@0.18.3 to fix
✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://security.snyk.io/vuln/SNYK-PYTHON-FUTURE-3180414] in future@0.18.2
introduced by future@0.18.2
Upgrade setuptools@58.0.4 to setuptools@65.5.1 to fix
✗ Regular Expression Denial of Service (ReDoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3180412 …
```
> fix snyk import error

- .gitignore
- elliottlib/__init__.py
- setup.py
Fix the following error when invoking `elliott --version` on an installation without the source git repository:
```
LookupError: setuptools-scm was unable to detect version for /usr/local/lib/python3.11/site-packages.
```
Steps to reproduce:
```sh
pip install .
elliott --version
```
This can be solved by introducting setuptools_scm to write a file containing the to-be-installed version.
> Fix version detection error on pip installations

- elliottlib/bzutil.py
- requirements.txt
requests-kerberos doesn't work on macOS. Use reuqests-gssapi instead.
> Deprecate requests-kerberos again

- elliottlib/errata.py
https://issues.redhat.com/browse/ART-6054
This is to enable prepare_release.py to set advisory dependencies (read story for details)
To test, in elliott dir, open python shell
```python3
from elliottlib.errata import get_blocking_errata, set_blocking_errata
set_blocking_errata(110351,110349,"SHIPPED_LIVE")
get_blocking_errata(110351)
```
then unset it at https://errata.devel.redhat.com/errata/edit_depends_on/110351
Keep in mind errata endpoints are weird
- The /erratum/{id} response doesn't mention blocking state
- The /blocking_errata_for/{id} response gives advisory in a weird format `{ "2023:0778": "SHIPPED_LIVE"}`. So I'm content to check just the advisory ids from erratum endpoint and trust that the state would be correct.
- The set blocker errata and set blocker state for advisory …
> ART-6054 Add blocking errata API calls

- elliottlib/cli/verify_attached_operators_cli.py
- elliottlib/gitdata.py
This issue is reported by Snyk. Use `yaml.safe_load` instead.
> Fix CWE-502: Deserialization of Untrusted Data

- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_verify_attached_bugs_cli.py
Often times, we would complain about on_qa to on_qa bugs
when checking for regression, which creates confusion 
when it is posted on #forum-release as part of check-bugs
(https://redhat-internal.slack.com/archives/CJARLA942/p1677594929245159)
But this case is not regression, 
(regression would be if the blocking bug (e.g. 4.11) status is modified, 
and blocked bug (backported bug e.g. 4.10) is on_qa). So ignore this case
> Ignore on_qa bugs when checking for regression

- elliottlib/bzutil.py
Elliott uses timestamps encoded in image NVRs to estimate the bug cutoff timestamp when sweeping bugs with a Brew event.
When there is a new image added to ocp-build-data, the build might not exist at the moment of the Brew event. Then we will see an error like:
```
OSError: No builds detected for using prefix: 'nmstate-console-plugin-container-v4.13.', extra_pattern: '*', assembly: 'stream', build_state: 'COMPLETE', el_target: 'None'
```
We need to update `bzutil.approximate_cutoff_timestamp` to ignore non-existent builds when estimating cutoff timestamps.
> Fix an issue in bug cutoff timestamps estimate

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_blocker_cli.py
- elliottlib/cli/find_bugs_qe_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_find_bugs_sweep_cli.py
This feature is requested by OpenShift QE to find CVE trackers against a release branch.
> ART-6236: find-bugs:sweep: Add --cve-only option

- elliottlib/bzutil.py
- tests/test_bzutil.py
Follow up to https://github.com/openshift-eng/elliott/pull/487
attach-cve-flaws fails when package_state is missing in hyrda response
Test: `elliott -g openshift-4.13 --assembly rc.0 attach-cve-flaws -a 111419 --noop`
Missing package_state can mean there are no unfixed components
Wait for Prodsec confirmation before merge: https://redhat-internal.slack.com/archives/CB95J6R4N/p1679348617881569
> [attach-cve-flaws] Handle missing "package state" when determining first fix

- elliottlib/cli/tarball_sources_cli.py
Ref. https://issues.redhat.com/browse/ART-6353
> Update tarball-sources output to account for the new spmm-utils host

- .devcontainer/dev.Dockerfile
- .devcontainer/devcontainer.json
Newer versions of pip and setuptools are required to use `pip install -e`
> Fix devcontainer to use pyproject.toml

- elliottlib/bzutil.py
- elliottlib/errata_async.py
We are doing an ET lookup for all found jira bugs - newly created jira bugs
will 404 since they are not sync'd. Handle that error instead of crashing
Tested with: `./elliott --data-path ../ocp-build-data -g openshift-4.14 --assembly stream find-bugs:sweep`
(without it) `2023-03-27 11:02:30,820 ERROR exception with jira bug tracker: 404, message='Not Found', url=URL('https://errata.devel.redhat.com/jira_issues/OCPBUGS-10908/advisories.json')`
> Ignore when new jira bugs are not found in ET

- elliottlib/errata.py
Right now we're using these library funcs in prepare_release.py in aos-cd-jobs
https://github.com/openshift-eng/aos-cd-jobs/blob/ca376b5909e85a544db3d6810196e24b29dc8d91/pyartcd/pyartcd/pipelines/prepare_release.py#L640 
Instead of having the caller figure out when something is wrong, 
raise error here.
> Raise error if advisory info not found

- elliottlib/bzutil.py
Bugs other than tracker bugs can have whiteboard components defined - currently we are detecting them as invalid trackers but they aren't. (https://bugzilla.redhat.com/show_bug.cgi?id=2092289)
> [verify-bugs] Don't error if a bug has whiteboard component defined

- elliottlib/cli/verify_cvp_cli.py
Fix the following error:
```
$ elliott -g openshift-4.13 --assembly rc.3 verify-cvp --all
File "/mnt/workspace/users/yuxzhu/elliott/elliottlib/cli/verify_cvp_cli.py", line 162, in verify_cvp_cli
if failed or failed_optional:
UnboundLocalError: local variable 'failed_optional' referenced before assignment
```
> verify-cvp: Fix missing variable failed_optional

- elliottlib/errata_async.py
- tests/test_errata_async.py
API /api/v1/erratum/{id}/builds_list seems to be problematic. With advisory 114782 it is missing one build.
Use /api/v1/erratum/{id}/builds instead.
> Move to another API to list advisory builds

- elliottlib/cli/__main__.py
- elliottlib/cli/find_bugs_kernel_cli.py
- elliottlib/cli/find_bugs_kernel_clones_cli.py
- elliottlib/config_model.py
- elliottlib/runtime.py
- pyproject.toml
- tests/test_find_bugs_kernel_cli.py
- tests/test_find_bugs_kernel_clones_cli.py
- `find-bugs:kernel --clone`: scan KMAINT trackers for kernel bugs, clone them into OCP (skip already cloned bugs), and make comments on those KMAINT trackers if builds are tagged.
- `find-bugs:kernel-clones --move`: move cloned kernel bugs to MODIFIED if corresponding builds are tagged into OCP candidate Brew tag (rhaos-x.y-rhel-z-candidate). Those MODIFIED bugs can be swept by ART's normal bug sweep and attached to Errata afterwards.
> [ART-6964] New commands to clone and move kernel bugs

- elliottlib/cli/__main__.py
- elliottlib/cli/move_builds_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/verify_attached_operators_cli.py
Sometimes we need the ability to simply move builds from one advisory to another
exactly without needing to worry about reanalyzing brew/tags/ET and an extra build slipping in
, like when preparing optional operator advisory at GA time or otherwise in special cases
`elliott move-builds --from 123 --to 456 -k image --noop`
This was tested with this week's release advisories (moving builds from extras -> image)
> Add Move builds command

- elliottlib/cli/find_bugs_kernel_cli.py
Jira search has a tendency to flake once in a while and throw a 401, take care of that
> Retry jira search when searching for kernel bugs

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_qe_cli.py
- tests/test_find_bugs_qe_cli.py
stdout isn't being forwarded from elliott find-bugs:qe in ocp4 job,
so use logger instead.
slack ref: https://redhat-internal.slack.com/archives/GDBRP5YJH/p1686309961426089?thread_ts=1686302994.401709&cid=GDBRP5YJH
> find-bugs:qe - Use local logger instead of click.echo

- pyproject.toml
When we do pip install for elliott in merged art-tools repo, setuptools requires it to be a git repo (submodule), which elliott will no longer be.
> remove setuptools-sm for art-tools merger

- pyproject.toml
The environment running our github actions doesn't have git. Let's move errata-tool to the PyPI version before making any changes on the github action image.
> Use errata-tool from PyPI

- elliottlib/bzutil.py
- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/cli/find_bugs_blocker_cli.py
- elliottlib/cli/find_bugs_kernel_cli.py
- elliottlib/cli/find_bugs_kernel_clones_cli.py
- elliottlib/cli/find_bugs_qe_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/repair_bugs_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/runtime.py
- tests/test_find_bugs_kernel_cli.py
- tests/test_find_bugs_kernel_clones_cli.py
Ref. https://issues.redhat.com/browse/ART-7268
- rename `runtime.bug_trackers` into `runtime.get_bug_tracker`; the function returns a single object, and it's not a property so making this clear in the name. Also added return type hint: https://github.com/openshift-eng/elliott/commit/3a43d552a7b5d61b77b7ae2056b7109ae92a4f68
- when moving MODIFIED bugs to QE, if the bug visibility is by any means restricted, add a comment stating that the bug won't be visible in the advisory: https://github.com/openshift-eng/elliott/commit/9f8321303caff6d15e59e491bae77f3b890cf03b
> ART-7268 Say in bug that it will not be visible in advisory if so
