openshift-eng/elliott

- elliottlib/schema_image.yml
@smunilla - Without this elliott will break later today
> Adding required flag to schema

- elliott
- elliottlib/bzutil.py
- elliottlib/constants.py
- elliottlib/errata.py
- elliottlib/util.py
- Allow RHSA creation
- Add search command for CVE trackers
- More explicitly filter out security issues for regular bug sweeps
> Enable security advisory workflow

- elliottlib/schema_group.yml
Companion to https://github.com/openshift/doozer/pull/58
> schema_group.yml: add use_source_fallback_branch

- elliott
Make exception handling more consistent across the board.
> Fix error handling

- elliottlib/config.py
Any reason these weren't handled in #21?
> Fix further unsafe yaml loading.

- elliott
It turns out we already store this information in group.yaml
> Get brew tag from group branch

- elliott
Something changed with the BZ api and this wasn't working anymore. I also
added the ability to specify specific IDs if desired.
> Fix repair-bugs command

- elliott
- elliottlib/openshiftclient.py
This will let us find bugs and builds that have changed between two image payloads.
> Update find-bugs and find-builds for payload diffs

- elliott
- elliottlib/runtime.py
- requirements.txt
Working toward automating signed compose (ART-308)
> enable using default advisories, expose more errata info

- .gitignore
- tox.ini
First step towards running tox on Travis.
Related ticket: https://jira.coreos.com/browse/ART-544
> [ART-544] (part 1 of 4) Config tox to run flake and unit tests

- elliottlib/assertion.py
- elliottlib/brew.py
- elliottlib/bzutil.py
- elliottlib/bzutil_test.py
- elliottlib/config.py
- elliottlib/container_test.py
- elliottlib/errata.py
- elliottlib/errata_test.py
- elliottlib/exceptions.py
- elliottlib/image.py
- elliottlib/image_test.py
- elliottlib/metadata.py
- elliottlib/metadata_test.py
- elliottlib/model.py
- elliottlib/openshiftclient.py
- elliottlib/rpmcfg.py
- elliottlib/rpmcfg_test.py
- elliottlib/runtime.py
- elliottlib/util.py
Since the next step is to have Travis running `flake8`,
would be nice to not have it failing due to linting issues.
> [ART-544] (part 2 of 4) Make flake8 happy ;D

- elliott
- elliottlib/cli/common.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/constants.py
- elliottlib/util.py
This is actually prep for something else, but there were a lot of things I wanted to fix along the way.
- being able to do `--use-default-advisory extras|metadata`
- ridiculously slow auth test 
- https://jira.coreos.com/browse/ART-1106
The rest is refactoring. Best to review one commit at a time...
> Refactor find_builds and fix some minor things

- elliottlib/brew.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/config.py
- elliottlib/image.py
- elliottlib/runtime.py
an alternative solution for https://github.com/openshift/elliott/pull/60 without touching errata-tool
> ART-1062 adding find-builds suport attach multiple images with different pv

- elliottlib/openshiftclient.py
Fixes https://jira.coreos.com/browse/ART-1162
It was failing because it expected a brew component label in
machine-os-content. We don't want that in the list of things to add to
an advisory anyway.
Also added helpful debug in case anything else like this comes up.
> [ART-1162] fix find-builds --between

- elliott
- elliottlib/cli/puddle_advisories_cli.py
- elliottlib/constants.py
- elliottlib/errata.py
I just had a few tweaks to add on to https://github.com/openshift/elliott/pull/63
> ART-1069: elliott puddle-advisories misses some advisory metadata

- elliottlib/cli/common.py
- elliottlib/dotconfig.py
- requirements.txt
So that we can make quick changes to the one-file library and that will help our Python 3 migration.
See https://jira.coreos.com/browse/ART-1180.
> Embed pydotconfig into elliott

- README.md
- elliottlib/dotconfig.py
- elliottlib/gitdata.py
Hi @adammhaile, thank you for letting us know about this issue, would love to have your review.
> License dotconfig and gitdata under LGPL v3

- elliottlib/brew.py
- elliottlib/cli/__main__.py
- elliottlib/cli/add_metadata_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/constants.py
- elliottlib/util.py
- tests/test_errata.py
- tests/test_find_builds_cli.py
- tests/test_util.py
This is the same PR with https://github.com/openshift/elliott/pull/103, but that one had some problems with CI pip install yaml package.
> [ART-1176] refactoring elliott find_builds_cli.py bug fixes and removing branch option and product_version

- elliottlib/cli/tarball_sources_cli.py
https://issues.redhat.com/browse/ART-1618
> [ART-1618] Change destination of tarball sources

- elliottlib/cli/rpmdiff_cli.py
this is still an early experiment since I do not know what information we need to display and what kind of structure of yaml/json we need here, currently I just grab all the dict info I could get and dump it all.
https://issues.redhat.com/browse/ART-1392 
@vfreex @sosiouxme 
yaml output: https://gist.github.com/shiywang/c3a37e91e4ecce22da9c3b2a6b1e85f9
json output: https://gist.github.com/shiywang/8769052c1119cc5dd56d1ec96c2de45b
> [ART-1392] add json/yaml format print to rpmdiff show

- elliottlib/cli/tarball_sources_cli.py
https://issues.redhat.com/browse/ART-1618?focusedCommentId=14046662&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14046662
> Use new location of tarball sources by default

- elliottlib/cli/find_builds_cli.py
- elliottlib/errata.py
@vfreex @sosiouxme  As a follow-up PR of https://github.com/openshift/elliott/pull/129 as you guys suggested, now I made a distinction for both `--clean` and `--remove` usage:
`--clean` is used to remove the builds on errata by errata API (which I introduced a new func called get_brew_builds) 
`--remove` is only used with `-b` to remove specific builds for now.
I tested with https://errata.devel.redhat.com/advisory/55229
```
[dev@a2d3dd7146c9 elliott]$  cd /workspaces/elliott ; env /usr/bin/python3 /home/dev/.vscode-server/extensions/ms-python.python-2020.5.80290/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher 42255 -- /workspaces/elliott/elliott -g openshift-4.3 find-builds -k image --use-default-advisory image --clean 
2020-05-28 10:45:30,735 INFO Data clone directory already …
```
> adding another flag --clean

- elliottlib/cli/find_builds_cli.py
After attaching images to an advisory, configure advisory CDN repos
based on ocp-build-data.
This behavior can be opted out using `--no-cdn-repos`.
ocp-build-data updates:
- 4.4 https://github.com/openshift/ocp-build-data/pull/474
- 4.3 https://github.com/openshift/ocp-build-data/pull/475
- 4.2 https://github.com/openshift/ocp-build-data/pull/476
- 3.11 https://github.com/openshift/ocp-build-data/pull/477
- 4.6 https://github.com/openshift/ocp-build-data/pull/478
- 4.5 https://github.com/openshift/ocp-build-data/pull/479
> ART-1864: Set advisory CDN repos when sweeping images

- .devcontainer/dev.Dockerfile
- Bump base image to Fedora 32
- Remove Python 2 packages
- Use latest oc
> Update dev container Dockerfile

- y-stream/y-stream-trackers.py
- Didn't work at all with python3
- Allow TR parameter
> Make y-stream-trackers.py slightly more usable

- elliottlib/bzutil.py
- elliottlib/cli/__main__.py
Move bugs that are in MODIFIED state to ON_QA for testing. Also, take `--dry-run` better into account.
> [ART-2058] find-bugs: mode qe

- .devcontainer/README.md
- .devcontainer/dev.Dockerfile
- elliottlib/cli/__main__.py
- elliottlib/cli/find_bugs_cli.py
First two commits I updated along the way, final commit implements the feature.
- minor dev env updates
- move find-bugs into its own module
- https://issues.redhat.com/browse/ART-2060
> [ART-2060] elliott find-bugs --cve-trackers

- y-stream/y-stream-trackers.py
> Use python-bz apikey from usual location in y-stream script

- elliottlib/cli/attach_cve_flaws_cli.py
Earlier we were getting target_release out of [ocp-build-data's bugzilla.yml](https://github.com/openshift/elliott/blob/master/elliottlib/cli/attach_cve_flaws_cli.py#L59) instead we need to fetch it from the tracker bug(s). 
If there are conflicting target_release values found for tracker bugs, the script notifies and fails.
> ART-2520 (2) Fix target_release fetched from bz instead of git data

- Makefile
- elliottlib/cli/find_bugs_cli.py
- mypy.ini
- requirements-dev.txt
- tests/test_find_bugs_cli.py
- https://issues.redhat.com/browse/ART-2452
- [duplicate] https://issues.redhat.com/browse/ART-2640
List mode was broken as in the correct variables weren't being set, too many branching conditions in one huge function being one of the main problems which is hurting us here. I extracted out the mode into its own function. Wanted to keep the PR clean and limit the scope so I intentionally left out the other modes as is, for another PR.
- Remove placeholder bug 1931306 from rpm advisory https://errata.devel.redhat.com/advisory/69705
- Attach it `./elliott -g openshift-4.6 --debug find-bugs --mode list --id 1931306 --use-default-advisory rpm`
- Verify it worked
> ART-2452 Fix list mode

- elliottlib/brew.py
- elliottlib/build_finder.py
- elliottlib/cli/common.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/metadata.py
- elliottlib/rpmcfg.py
- elliottlib/runtime.py
- elliottlib/util.py
- tests/test_build_finder.py
- tests/test_find_builds_cli.py
- tests/test_imagecfg.py
- tests/test_metadata.py
- tests/test_util.py
Most of the code is taken from Doozer, but also tweaked to use in Elliott without porting too much code from Doozer.
This PR includes https://github.com/openshift/elliott/pull/204.
> ART-3057: find-builds full assembly awareness

- elliottlib/attach_cve_flaws.py
In [my last PR](https://github.com/openshift/elliott/pull/201) we fixed the issue of not failing 
but the function return value wasn't accurate.
If additional trackers are not found for the flaw bug
then the flaw bug IS considered a first fix.
[relevant slack thread](https://coreos.slack.com/archives/CB95J6R4N/p1625775501275100)
> ART-3095 Flaw bugs with no additional trackers are considered first fixes

- elliottlib/cli/change_state_cli.py
https://issues.redhat.com/browse/ART-3138
`elliott -g openshift-4.7 change-state -s QE --default-advisories --dry-run`
> ART-3138 Change state of all advisories for a release

- elliottlib/cli/find_bugs_cli.py
When preparing releases, sometimes we have new nightlies, when new bugs/builds need to be attached to advisories. In this case we don't want to use sweep, but still be able to provide a list of bugs to be attached. For that we have list mode.
In sweep mode we have filtering to determine which bugs go where (rpm component, extras components), which is not present in list. This change brings that to list mode
`elliott -g openshift-4.8 find-bugs --mode list --id 1981871,1970975,1981633,1982250,1982252,1980788,1981871 --into-default-advisories --dry-run`
> default advisories with list mode

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_cli.py
Add a message in comment give a next release version and use next next Monday as planed release date when move bug to QA.
> [art-3001] Add comment when move bug to QA

- elliottlib/cli/validate_rhsa.py
... since our promote job is calling this indiscriminately with all advisories
> validate-rhsa: exit quietly if not RHSA

- elliottlib/cli/find_builds_cli.py
This issue occurs when we attach kernel rpms defined as group
dependencies to 4.8.11 advisory.
Unlike member rpms, group dependencies are packages that are not built or
managed by ART. We need to check if they have valid `rhaos-` tags and
attach them if they do.
> Fix a find-builds issue with assemblies

- elliottlib/bzutil.py
- tox.ini
Until https://github.com/python-bugzilla/python-bugzilla/issues/149 is
resolved and the python-bugzilla library takes care of pagination,
implement limit/offset searching here.
> Bugzilla: Query again if results equals limit

- elliottlib/cli/attach_cve_flaws_cli.py
- tests/test_attach_cve_flaws_cli.py
https://issues.redhat.com/browse/ART-2720
This will require update to erratatool.yml in all current branches. So don't merge before all those are updated.
> ART-2720 Automate description update at RHSA conversion

- elliottlib/tarball_sources.py
entry.type only return number not str
> [ART-3684] fix entry type check

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yaml
- elliottlib/attach_cve_flaws.py
- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/find_bugs_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/errata_async.py
- tests/test_attach_cve_flaws.py
- tests/test_attach_cve_flaws_cli.py
- tests/test_errata_async.py
- attach-cve-flaws: associate builds with CVE bugs after flaw bugs are attached
- verify-attached-bugs: verify that CVE bugs are correctly associate attached builds
> [ART-2682] Associate builds with CVE bugs

- elliottlib/cli/__main__.py
- tests/test_bzutil.py
add auto option for remove-bugs
add comment option and close-placeholder option for repair-bugs
rebase from https://github.com/openshift/elliott/pull/241
> [ART-2880] enhance repair-bugs and remove-bugs

- elliottlib/util.py
Error:
```
$ ./elliott go -a RHBA-2021:1321 -c kiali
File "/home/sfowler/code/elliott/./elliott", line 11, in <module>
main()
File "/home/sfowler/code/elliott/elliottlib/cli/__main__.py", line 715, in main
cli(obj={})
File "/home/sfowler/.virtualenvs/elliott/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/home/sfowler/.virtualenvs/elliott/lib/python3.9/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/home/sfowler/.virtualenvs/elliott/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/home/sfowler/.virtualenvs/elliott/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
return …
```
> Fix error getting go version from el7 build log

- y-stream/y-stream-trackers.py
Fixes two issues:
- Lack of handling for BZ pagination
- Incorrect sorting/comparsion of semver target releases
This standalone script is only really useful for human review of Y-stream errata, I'm not sure if the core elliotlib code may also have a similar issue with comparison of target releases.
> Fixes for y-stream cve first fix script

- elliottlib/bzutil.py
- elliottlib/cli/find_builds_cli.py
- elliottlib/cli/verify_cvp_cli.py
- elliottlib/exectools.py
- elliottlib/metadata.py
- elliottlib/runtime.py
- requirements.txt
- tests/test_metadata.py
Requires https://github.com/openshift/elliott/pull/271
> verify-cvp: assembly awareness

- elliottlib/cli/verify_attached_bugs_cli.py
Let's make this even more readable and compact
> Minor formatting change to verify bugs slack output

- elliottlib/bzutil.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
refactor create bug function used by create placeholder bug and create text_only bug
> [ART-3826] refactor create bug function

- elliottlib/cli/find_bugs_cli.py
- tests/test_find_bugs_cli.py
This is replaced by elliott attach-bugs
> Remove list mode from find-bugs

- elliottlib/cli/verify_attached_bugs_cli.py
When running `verify-attached-bugs` for RHBA which were previously an
RHSA, a lot of CVE flaw related checks will fail because Errata has some
records (like CVE Names and CVE package exclusions) remained.
We need to skip those checks if the advisory is RHBA.
This PR also adds a check to raise an error if the advisory is not RHSA and
first-fix flaw bugs are attached.
> verify-attached-bugs: Don't fail on RHBA

- elliottlib/bzutil.py
we can also set status to VERIFIED when create bug
> set target_release when create bug

- elliottlib/assertion.py
- functional_tests/README.md
- functional_tests/test_find_bugs_blocker.py
- functional_tests/test_find_bugs_qe.py
- functional_tests/test_find_bugs_sweep.py
- functional_tests/test_poll_signed.py
- functional_tests/test_rpmdiff.py
- requirements.txt
- y-stream/y-stream-trackers.py
> Remove Python 2 leftovers

- elliottlib/bzutil.py
- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- tests/test_bzutil_jira.py
- tests/test_find_bugs_sweep_cli.py
References
- jql date format https://support.atlassian.com/jira-software-cloud/docs/advanced-search-reference-jql-fields/
- before function https://support.atlassian.com/jira-software-cloud/docs/advanced-search-reference-jql-operators/
> Sweep brew event with jira

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_sweep_cli.py
- tests/test_find_bugs_sweep_cli.py
rebase from https://github.com/openshift/elliott/pull/331
> Fix bug categorization issue with sub_components

- elliottlib/bzutil.py
- elliottlib/cli/create_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/gitdata.py
- elliottlib/runtime.py
- functional_tests/test_advisory_images.py
- functional_tests/test_create.py
- functional_tests/test_find_bugs_blocker.py
- functional_tests/test_find_bugs_qe.py
- functional_tests/test_find_bugs_sweep.py
- functional_tests/test_find_builds.py
- functional_tests/test_get.py
along with changes in ocp-build-data
4.10: https://github.com/openshift/ocp-build-data/pull/1592
4.9: https://github.com/openshift/ocp-build-data/pull/1593
4.8: https://github.com/openshift/ocp-build-data/pull/1594
4.7: https://github.com/openshift/ocp-build-data/pull/1595
4.6: https://github.com/openshift/ocp-build-data/pull/1596
> [ART-4062] Consolidate jira and bugzilla component filter list into one

- elliottlib/cli/attach_bugs_cli.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/create_placeholder_cli.py
- elliottlib/cli/create_textonly_cli.py
- elliottlib/cli/find_bugs_qe_cli.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/remove_bugs_cli.py
- elliottlib/cli/repair_bugs_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- elliottlib/runtime.py
- tests/test_find_bugs_qe_cli.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_remove_bugs_cli.py
- tests/test_repair_bugs_cli.py
check env var `USEJIRA` in runtime
drop `--jira` parameter in the following cli
```
elliottlib/cli/repair_bugs_cli.py
elliottlib/cli/attach_bugs_cli.py
elliottlib/cli/create_placeholder_cli.py
elliottlib/cli/find_bugs_sweep_cli.py
elliottlib/cli/attach_cve_flaws_cli.py
elliottlib/cli/create_textonly_cli.py
elliottlib/cli/find_bugs_qe_cli.py
elliottlib/cli/verify_attached_bugs_cli.py
elliottlib/cli/remove_bugs_cli.py
```
> [ART-4061] use env var check whether enable jira bug

- elliottlib/bzutil.py
- tests/test_find_bugs_qe_cli.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_remove_bugs_cli.py
- tests/test_repair_bugs_cli.py
Branched off of https://github.com/openshift/elliott/pull/350 (Ignore those changes)
> bz query includes fields to fetch

- requirements.txt
Fix: https://github.com/thegreyd/errata-tool/commit/bad2cb9c3321a1179f018cd9ddcf1d51d634290b
> Use errata-tool fork with fix

- elliottlib/cli/create_placeholder_cli.py
xmlrpc.client.Fault: <Fault 106: 'Sorry, entering a bug into the product OpenShift Container Platform has been disabled.'>
[439](https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/439/console)
> Disable bz bug creation

- elliottlib/bzutil.py
https://coreos.slack.com/archives/C027ZPSD133/p1660747584146519
> Fix jira component search

- .devcontainer/dev.Dockerfile
- elliottlib/cli/verify_cvp_cli.py
- elliottlib/constants.py
- elliottlib/cvp.py
- elliottlib/exectools.py
- elliottlib/resultsdb.py
- elliottlib/util.py
- support printing CVP test results in yaml/json format
- support providing auto-fix suggestions in yaml/json
Used in https://github.com/openshift/aos-cd-jobs/pull/3164
> Various improvements in verify-cvp command

- elliottlib/cli/find_bugs_sweep_cli.py
- tests/test_find_bugs_sweep_cli.py
Fix for https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/450/console
> Get assembly bug ids by bug type

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
This is currently failing https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fcheck-bugs/506/console
> Ignore bugs of other projects before trying to fetch them

- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/constants.py
- tests/test_attach_cve_flaws_cli.py
when adjust security impact only adjust to higher impact
> fix-security-impact

- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_verify_attached_bugs_cli.py
Reverts openshift/elliott#395
This was merged in error - https://github.com/openshift/elliott/pull/403 is the PR where the fix is being worked upon
> Revert "exclude placeholder bug in bug sweep and fix RHSA check"

- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- elliottlib/cli/cli_opts.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_bzutil.py
- tests/test_verify_attached_bugs_cli.py
> Refactor and fix verify-attached-bugs 

- elliottlib/cli/attach_cve_flaws_cli.py
There is an issue with the order of converting RHBA to RHSA and associating CVEs with builds. We need to do it in the correct order and ensure that the association for JIRA bugs and bugzilla bugs don't override each other.
https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/481/console
```
2022-09-15 06:41:40,996 ERROR Traceback (most recent call last):
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/attach_cve_flaws_cli.py", line 128, in get_flaws
await associate_builds_with_cves(errata_api, advisory, attached_tracker_bugs, tracker_flaws, flaw_id_bugs, noop)
File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/attach_cve_flaws_cli.py" …
```
> attach-cve-flaws: fix CVEs not associated error

- elliottlib/cli/attach_cve_flaws_cli.py
1. AsyncErrataAPI shouldn't be closed inside of the loop because it is created outside of the loop. Use new AsyncErrataAPI instance for each advisory.
2. Don't panic on advisories without any trackers.
> Fix issues introduced by #426

- elliottlib/bzutil.py
Bugs fetched are not in order.
So this is a bug, which will make
us miss bugs
> Fix bug map bug

- elliottlib/cli/find_bugs_sweep_cli.py
- tests/test_find_bugs_sweep_cli.py
Also, remove some network interactions during tests
> bug sweep: Make unified report

- elliottlib/bzutil.py
- elliottlib/cli/attach_cve_flaws_cli.py
- tests/test_attach_cve_flaws_cli.py
- tests/test_bzutil.py
sort CVE bug list by it's impact and CVE number
> [ART-3778] sort CVEs in description

- elliottlib/bzutil.py
- elliottlib/errata.py
> Revert "[ART-4554] use errata_tool lib"

- elliottlib/bzutil.py
- elliottlib/errata.py
- requirements.txt
filter out attached bugs then add bugs with errata_tools
wait until we got this https://github.com/red-hat-storage/errata-tool/pull/234
> [ART-4554] use errata_tool add bugs

- elliottlib/bzutil.py
- elliottlib/errata.py
- requirements.txt
Reverts openshift/elliott#434
Exception was raised when this was used. Reverting for now.
> Revert "[ART-4554] use errata_tool add bugs"

- requirements.txt
similar issue with https://github.com/libgit2/pygit2/issues/1176
> pin pygit2 version

- elliottlib/bzutil.py
> optimize is_cve_in_summary function

- elliottlib/bzutil.py
- elliottlib/errata.py
- requirements.txt
REF: https://github.com/openshift/elliott/pull/434
> [ART-4554] use errata_tool add/remove jira issues

- elliottlib/cli/find_bugs_sweep_cli.py
Will try to avoid to directly use exit code. Let's raise an Exception to the top level instead.
> find-bugs:sweep: don't exit with 0 on error

- elliottlib/cli/advisory_drop_cli.py
move advisory to NEW_FILES before drop builds
test build https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/hack/job/ximhan/job/build%252Fdrop_advisories/4/console
> fix-drop-advisory

- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_find_bugs_sweep_cli.py
To work with https://art-docs.engineering.redhat.com/release/4.y-ga/#early-silent-operator-release
> Allow metadata advisory to have trackers

- elliottlib/bzutil.py
- tests/test_bzutil.py
https://redhat-internal.slack.com/archives/CJARLA942/p1673620364882949?thread_ts=1673431938.389529&cid=CJARLA942
> First fix - Don't consider fix_state

- elliottlib/bzutil.py
See for example https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/630/console
> Fix unclosed session error

- elliottlib/bzutil.py
https://redhat-internal.slack.com/archives/G01HDTRUU3T/p1674183594405019
> Complain if target version field is missing

- elliottlib/cli/find_builds_cli.py
Remove all occurrences of `asyncio.get_event_loop().run_until_complete()`
> Make elliott find-builds async

- elliottlib/brew.py
elliott go is broken for rhel9 rpms
> [go] Support rhel9 rpms

- .github/workflows/snyk_security.yaml
Setup snyk (https://issues.redhat.com/browse/ART-6354)
Steps
- Get the github token by following this [doc](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/authenticating-as-a-github-app-installation) using openshift-art-build-bot credentials on bitwarden. Generate a JWT token first and using that generate a github token
- Add a secret to the repo by using GitHub API endpoint ([docs](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#create-or-update-a-repository-secret)) _(but make sure to check if a secret with the same name doesn't exist, else the new value will overwrite the old one!)_
- You will need the repository public key, which you can get from [here](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#get …
> [ART-6354] Setup synk

- elliottlib/cli/find_bugs_qe_cli.py
- elliottlib/errata_async.py
- tests/test_find_bugs_qe_cli.py
[slack with vikas](https://redhat-internal.slack.com/archives/GDBRP5YJH/p1679688236206759?thread_ts=1679685444.078899&cid=GDBRP5YJH)
> fix confusing jira msging

- elliottlib/bzutil.py
- elliottlib/cli/find_bugs_sweep_cli.py
- elliottlib/cli/verify_attached_bugs_cli.py
- tests/test_bzutil.py
- tests/test_find_bugs_sweep_cli.py
- tests/test_verify_attached_bugs_cli.py
Follow up to https://github.com/openshift-eng/elliott/pull/541
> Invalid tracker bug followup

- elliottlib/cli/verify_attached_bugs_cli.py
A validation in `verify-attached-bugs` is checking if all blocking bugs in the previous minor version are already addressed (in VERIFIED or later state). However, I noticed the following error when running it for 4.13 rc.3:
```
File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/elliott/elliottlib/cli/verify_attached_bugs_cli.py", line 176, in validate
blocking_bugs_for = self._get_blocking_bugs_for(non_flaw_bugs)
File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/elliott/elliottlib/cli/verify_attached_bugs_cli.py", line 367, in _get_blocking_bugs_for
next_target = any(is_next_target(target) for target in bug.target_release)
File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/elliott/elliottlib/bzuti …
```
> verify-attached-bugs: Fix Target Version not set error

- elliottlib/assembly.py
- elliottlib/cli/__main__.py
- elliottlib/cli/find_unconsumed_rpms.py
- elliottlib/rhcos.py
This command will list all tagged rpms that are not used in RHCOS or any images.
> Add `find-unused-rpms` to find unused rpms

- elliottlib/cli/find_builds_cli.py
- elliottlib/cli/verify_attached_operators_cli.py
This part is needed to shuffle builds around when preparing silent operator advisory
> [verify-attached-operators] Print command to shuffle builds

- .github/workflows/tests.yaml
- Makefile
https://issues.redhat.com/browse/ART-6367
> ART-6367 Run unit tests on gh actions

- elliottlib/cli/find_bugs_kernel_clones_cli.py
Ref. https://issues.redhat.com/browse/ART-7132
> Wrap search for Jira issues with retry

- pyproject.toml
advisory schema changed, errata_tool need update
> use hack errata_tool

- pyproject.toml
Reverts openshift-eng/elliott#567
> Revert "use hack errata_tool"

- elliottlib/bzutil.py
See: https://issues.redhat.com/browse/ART-7053
> Add comment about jira field ids

- elliottlib/cli/verify_attached_bugs_cli.py
align with https://github.com/openshift-eng/elliott/pull/569
> Don't error out if CVE has a non-CVE alias
